USE [master]
GO
-- Check if the database "PropNote" exists
IF DB_ID('PropNote') IS NOT NULL
BEGIN
    -- Drop the database if it exists
    ALTER DATABASE PropNote SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PropNote;
END
/****** Object:  Database [PropNote]    Script Date: 2023/07/27 11:38:26 ******/
CREATE DATABASE [PropNote]
GO
ALTER DATABASE [PropNote] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PropNote] SET ARITHABORT OFF 
GO
ALTER DATABASE [PropNote] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PropNote] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PropNote] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PropNote] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PropNote] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PropNote] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PropNote] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PropNote] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PropNote] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PropNote] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PropNote] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PropNote] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PropNote] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PropNote] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PropNote] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PropNote] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PropNote] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PropNote] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PropNote] SET  MULTI_USER 
GO
ALTER DATABASE [PropNote] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PropNote] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PropNote] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PropNote] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PropNote] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PropNote] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PropNote] SET QUERY_STORE = OFF
GO
USE [PropNote]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCESS](
	[AccessID] [int] IDENTITY(1,1) NOT NULL,
	[AccessName] [varchar](50) NOT NULL,
	[AccessDescription] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AccessID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[AdminID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[Name] [varchar](100) NOT NULL,
	[PhoneNumber] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BROKER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BROKER](
	[BrokerID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Surname] [varchar](100) NOT NULL,
	[PhoneNumber] [varchar](10) NOT NULL,
	[OfficeAddress] [varchar](50) NOT NULL,
	[LicenseNumber] [varchar](100) NOT NULL,
	[CommissionRate] [decimal](5, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BrokerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTRACTOR]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTRACTOR](
	[ContractorID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[ContractorTypeID] [int] NULL,
	[AreaOfBusiness] [varchar](100) NULL,
	[Availability] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ContractorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTRACTORTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTRACTORTYPE](
	[ContractorTypeID] [int] IDENTITY(1,1) NOT NULL,
	[ContractorTypeName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ContractorTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Correspondance]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORRESPONDANCE](
	[CorrespondanceID] [int] IDENTITY(1,1) NOT NULL,
	[CorrespondanceName] [varchar](100) NULL,
	[CorrespondanceDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CorrespondanceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPOSIT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPOSIT](
	[DepositID] [int] IDENTITY(1,1) NOT NULL,
	[LeaseID] [int] NOT NULL,
	[Amount] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DepositID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Discount]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISCOUNT](
	[DiscountID] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[DiscountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Help]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HELP](
	[HelpID] [int] IDENTITY(1,1) NOT NULL,
	[FK_HelpCategoryID] [int] NULL,
	[HelpDescription] [varchar](50) NULL,
	[HelpVideo] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[HelpID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HelpCategory]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HELPCATEGORY](
	[HelpCategoryID] [int] IDENTITY(1,1) NOT NULL,
	[HelpCategoryDescription] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[HelpCategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LEASE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LEASE](
	[LeaseID] [int] IDENTITY(1,1) NOT NULL,
	[TenantID] [int] NULL,
	[PropertyID] [int] NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[MonthlyAmount] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[LeaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCE](
	[MaintenanceID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[ContractorID] [int] NULL,
	[MaintenanceStatusID] [int] NOT NULL,
	[MaintenanceTypeID] [int] NOT NULL,
	[MaintenanceDate] [date] NOT NULL,
	[MaintenanceTime] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCESTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCESTATUS](
	[MaintenanceStatusID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCETYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCETYPE](
	[MaintenanceTypeID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceTypeName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCENOTE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCENOTE](
	[MaintenanceNoteID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceID] [int] NOT NULL,
	[MaintenanceNoteDescription] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceNoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEETING]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEETING](
	[MeetingID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Date] [date] NOT NULL,
	[Time] [time](7) NOT NULL,
	[MeetingType] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEETINGMEMBERLINE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEETINGMEMBERLINE](
	[MeetingMemberID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingMemberID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER](
	[MeetingMemberID] [int] IDENTITY(1,1) NOT NULL,
	[MeetingMember] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingMemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[NotificationID] [int] IDENTITY(1,1) NOT NULL,
	[NotificationTypeID] [int] NULL,
	[ReccurenceTypeID] [int] NULL,
	[NotificationName] [varchar](50) NULL,
	[NotificationDate] [date] NULL,
	[StartTime] [time] NULL,
	[EndTime] [time] NULL,
	[Description] [varchar](max)
PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATIONTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATIONTYPE](
	[NotificationTypeID] [int] IDENTITY(1,1) NOT NULL,
	[NotificationTypeDescription] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificationTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROBLEM]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEM](
	[ProblemID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionID] [int] NOT NULL,
	[ProblemStatusID] [int] NOT NULL,
	[ProblemSubject] [varchar](32) NULL,
	[ProblemDescription] [varchar](100) NULL,
	[ProblemDate] [date] NULL,
	[ProblemSeverity] [varchar](20)
PRIMARY KEY CLUSTERED 
(
	[ProblemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemPhoto]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMPHOTO](
	[ProblemPhotoID] [int] IDENTITY(1,1) NOT NULL,
	[ProblemID] [int] NOT NULL,
	[ImageName] [varchar](max) NULL,
	[ImageData] [varchar] (max),
	[UploadDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemPhotoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemStatus]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMSTATUS](
	[ProblemStatusID] [int] NOT NULL,
	[ProblemStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemVideo]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMVIDEO](
	[ProblemVideoID] [int] IDENTITY(1,1) NOT NULL,
	[ProblemID] [int] NOT NULL,
	[FileName] [nvarchar](255) NULL,
	[ContentType] [nvarchar](100) NULL,
	[UploadDate] [date] NULL,
	[VideoData] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemVideoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTY]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTY](
	[PropertyID] [int] IDENTITY(1,1) NOT NULL,
	[BrokerID] [int] NULL,
	[PropertyStatusID] [int] NULL,
	[Description] [varchar](100) NULL,
	[BuildingNumber] [int] NULL,
	[Street] [varchar](100) NULL,
	[Suburb] [varchar](100) NULL,
	[PurchaseAmount] [decimal](20, 2) NULL,
	[PurchaseYear] [int] NULL,
	[Size] [decimal](10, 2) NULL,
	[Yard] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTYIMAGE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTYIMAGE](
	[PropertyImageID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[ImageName] [varchar](max) NULL,
	[ImageData] nvarchar(max),
PRIMARY KEY CLUSTERED 
(
	[PropertyImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTYSTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTYSTATUS](
	[PropertyStatusID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recovery]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERY] (
	[RecoveryID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NULL,
	[RecoveryTypeID] [int] NULL,
	[RecoveryDescription] [varchar](50) NULL,
	[RecoveryAmount] [decimal] (10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[RecoveryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECOVERYTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERYTYPE] (
	[RecoveryTypeID] [int] IDENTITY(1,1) NOT NULL,
	[RecoveryTypeDescription] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[RecoveryTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTION]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTION] (
	[InspectionID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NULL,
	[EmployeeID] [int] NULL,
	[InspectionTypeID] [int] NULL,
	[InspectionStatusID] [int] NULL,
	[InspectionDescription] [varchar] (50) NULL,
	[InspectionDate] [date] NULL,
	[InspectionTime] [time] NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTIONSTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTIONSTATUS] (
	[InspectionStatusID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionStatusName] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTIONTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTIONTYPE] (
	[InspectionTypeID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionTypeName] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLISTITEM]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLISTITEM](
	[SnagListItemID] [int] IDENTITY(1,1) NOT NULL,
	[SnagListItemDescription] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SnagListItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLIST]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLIST](
	[SnagListID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[SnagListDescription] [varchar](100) NULL,
	[SnagListCreated] [date],
	[SnagListModified] [date],
PRIMARY KEY CLUSTERED 
(
	[SnagListID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLISTITEMLINE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLISTITEMLINE](
	[SnagListID] [int] NOT NULL,
	[SnagListItemID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SnagListID] ASC,
	[SnagListItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[RECCURENCEITEMTYPE]]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECCURENCEITEMTYPE](
	[ReccurenceTypeID] [int] IDENTITY(1,1) NOT NULL,
	[ReccurenceTypeDescription] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ReccurenceTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHEDULE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHEDULE](
	[NotificationID]  [int] NOT NULL,
	[UserID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TENANT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TENANT](
	[TenantID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[CompanyName] [varchar](100) NULL,
	[CompanyNumber] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[TenantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[JobTitle] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAccess]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERACCESS](
	[RoleID] [int] NOT NULL,
	[AccessID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[AccessID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERMEETING]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERMEETING](
	[UserID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERROLE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERROLE](
	[RoleID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](255) NOT NULL,
	[Password] [varchar](255) NOT NULL,
	[ProfilePhoto] [varchar](max) NULL,
	[Email] [varchar](255) NOT NULL,
	[Name] [varchar](255) NULL,
	[Surname] [varchar](255) NULL,
	[PhoneNumber] [varchar](10) NULL,
	[HasLoggedIn] [bit] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VAT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAT](
	[VATID] [int] IDENTITY(1,1) NOT NULL,
	[Percentage] [decimal](5, 2) NULL,
	[Date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[VATID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[PaymentID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceID] [int] NOT NULL,
	[Amount] [decimal] (10,2) NULL,
PRIMARY KEY CLUSTERED 
(
	[PaymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENT] WITH CHECK ADD FOREIGN KEY([MaintenanceID])
REFERENCES [dbo].[MAINTENANCE] ([MaintenanceID])
GO
ALTER TABLE [dbo].[ADMIN] WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[CONTRACTOR]  WITH CHECK ADD FOREIGN KEY([ContractorTypeID])
REFERENCES [dbo].[CONTRACTORTYPE] ([ContractorTypeID])
GO
ALTER TABLE [dbo].[CONTRACTOR]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[DEPOSIT]  WITH CHECK ADD FOREIGN KEY([LeaseID])
REFERENCES [dbo].[LEASE] ([LeaseID])
GO
ALTER TABLE [dbo].[HELP]  WITH CHECK ADD FOREIGN KEY([FK_HelpCategoryID])
REFERENCES [dbo].[HELPCATEGORY] ([HelpCategoryID])
GO
ALTER TABLE [dbo].[LEASE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[LEASE]  WITH CHECK ADD FOREIGN KEY([TenantID])
REFERENCES [dbo].[TENANT] ([TenantID])
GO
ALTER TABLE [dbo].[SCHEDULE] WITH CHECK ADD FOREIGN KEY([NotificationID])
REFERENCES [dbo].[NOTIFICATION] ([NotificationID])
GO
ALTER TABLE [dbo].[SCHEDULE] WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD FOREIGN KEY([ReccurenceTypeID])
REFERENCES [dbo].[RECCURENCEITEMTYPE] ([ReccurenceTypeID])
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD FOREIGN KEY([NotificationTypeID])
REFERENCES [dbo].[NOTIFICATIONTYPE] ([NotificationTypeID])
GO
ALTER TABLE [dbo].[MEETINGMEMBERLINE]  WITH CHECK ADD FOREIGN KEY([MeetingMemberID])
REFERENCES [dbo].[MEMBER] ([MeetingMemberID])
GO
ALTER TABLE [dbo].[MEETINGMEMBERLINE]  WITH CHECK ADD FOREIGN KEY([MeetingID])
REFERENCES [dbo].[MEETING] ([MeetingID])
GO
ALTER TABLE [dbo].[PROPERTY]  WITH CHECK ADD FOREIGN KEY([BrokerID])
REFERENCES [dbo].[BROKER] ([BrokerID])
GO
ALTER TABLE [dbo].[PROPERTY]  WITH CHECK ADD FOREIGN KEY([PropertyStatusID])
REFERENCES [dbo].[PROPERTYSTATUS] ([PropertyStatusID])
GO
ALTER TABLE [dbo].[PROPERTYIMAGE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[TENANT]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERACCESS]  WITH CHECK ADD FOREIGN KEY([AccessID])
REFERENCES [dbo].[ACCESS] ([AccessID])
GO
ALTER TABLE [dbo].[USERACCESS]  WITH CHECK ADD FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLE] ([RoleID])
GO
ALTER TABLE [dbo].[USERMEETING]  WITH CHECK ADD FOREIGN KEY([MeetingID])
REFERENCES [dbo].[MEETING] ([MeetingID])
GO
ALTER TABLE [dbo].[USERMEETING]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERROLE]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERROLE]  WITH CHECK ADD FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLE] ([RoleID])
GO
ALTER TABLE [dbo].[PROBLEMVIDEO]  WITH CHECK ADD FOREIGN KEY([ProblemID])
REFERENCES [dbo].[PROBLEM] ([ProblemID])
GO
ALTER TABLE [dbo].[PROBLEMPHOTO]  WITH CHECK ADD FOREIGN KEY([ProblemID])
REFERENCES [dbo].[PROBLEM] ([ProblemID])
GO
ALTER TABLE [dbo].[PROBLEM]  WITH CHECK ADD FOREIGN KEY([InspectionID])
REFERENCES [dbo].[INSPECTION] ([InspectionID])
GO
ALTER TABLE [dbo].[PROBLEM]  WITH CHECK ADD FOREIGN KEY([ProblemStatusID])
REFERENCES [dbo].[PROBLEMSTATUS] ([ProblemStatusID])
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([ContractorID])
REFERENCES [dbo].[CONTRACTOR] ([ContractorID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([MaintenanceStatusID])
REFERENCES [dbo].[MAINTENANCESTATUS] ([MaintenanceStatusID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([MaintenanceTypeID])
REFERENCES [dbo].[MAINTENANCETYPE] ([MaintenanceTypeID])
GO
ALTER TABLE [dbo].[MAINTENANCENOTE]  WITH CHECK ADD FOREIGN KEY([MaintenanceID])
REFERENCES [dbo].[MAINTENANCE] ([MaintenanceID])
GO
ALTER TABLE [dbo].[SNAGLISTITEMLINE]  WITH CHECK ADD FOREIGN KEY([SnagListItemID])
REFERENCES [dbo].[SNAGLISTITEM] ([SnagListItemID])
GO
ALTER TABLE [dbo].[SNAGLISTITEMLINE]  WITH CHECK ADD FOREIGN KEY([SnagListID])
REFERENCES [dbo].[SNAGLIST] ([SnagListID])
GO
ALTER TABLE [dbo].[SNAGLIST]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[RECOVERY]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[RECOVERY]  WITH CHECK ADD FOREIGN KEY([RecoveryTypeID])
REFERENCES [dbo].[RECOVERYTYPE] ([RecoveryTypeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([InspectionTypeID])
REFERENCES [dbo].[INSPECTIONTYPE] ([InspectionTypeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([InspectionStatusID])
REFERENCES [dbo].[INSPECTIONSTATUS] ([InspectionStatusID])
GO
USE [master]
GO
ALTER DATABASE [PropNote] SET  READ_WRITE 
GO

USE [PropNote]
GO
/*Add Seed Data*/
INSERT INTO [dbo].[ROLE]([Name])VALUES('Admin');
INSERT INTO [dbo].[ROLE]([Name])VALUES('Tenant');
INSERT INTO [dbo].[ROLE]([Name])VALUES('Broker');
INSERT INTO [dbo].[ROLE]([Name])VALUES('Contractor');
GO

INSERT INTO [dbo].[BROKER]
           ([Name]
           ,[Surname]
           ,[PhoneNumber]
           ,[OfficeAddress]
           ,[LicenseNumber]
           ,[CommissionRate])
     VALUES
           ('Eric'
           ,'Jarvie'
           ,'0815245184'
           ,'510 Durban Road'
           ,'6524548'
           ,2.5)
GO

INSERT INTO [dbo].[PROPERTYSTATUS]
           ([PropertyStatusName])
     VALUES
           ('Avaliable')
GO

INSERT INTO [dbo].[PROPERTY]
           ([BrokerID]
           ,[PropertyStatusID]
           ,[Description]
           ,[BuildingNumber]
           ,[Street]
           ,[Suburb]
           ,[PurchaseAmount]
           ,[PurchaseYear]
           ,[Size]
           ,[Yard])
     VALUES
           (1
           ,1
           ,'Factory'
           ,10
           ,'54'
           ,'Durban'
           ,2000000
           ,2018
           ,698
           ,3.6)
GO

INSERT INTO [dbo].[USER]
           ([Username]
           ,[Password]
           ,[ProfilePhoto]
           ,[Email]
           ,[Name]
           ,[Surname]
           ,[PhoneNumber]
           ,[HasLoggedIn])
     VALUES
           ('pip'
           ,'DEE6669875FFA6D6A8F8AD53DF4908E542780F2FC4221D6DE6958FCAF49D6E73'
           ,null
           ,'pipsjarvie@gmail.com'
           ,'Pippa'
           ,'Jarvie'
           ,'0835421542'
           ,1)
GO

INSERT INTO [dbo].[USERROLE]
           ([RoleID]
           ,[UserID])
     VALUES
           (1
           ,1)
GO

INSERT INTO [dbo].[PROPERTYIMAGE]
           ([PropertyID]
           ,[ImageName]
           ,[ImageData])
     VALUES
           (1
           ,'landingPageHouse.jpg'
           ,'/9j/4AAQSkZJRgABAQEASABIAAD/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFjcHJ0AAABUAAAADNkZXNjAAABhAAAAGx3dHB0AAAB8AAAABRia3B0AAACBAAAABRyWFlaAAACGAAAABRnWFlaAAACLAAAABRiWFlaAAACQAAAABRkbW5kAAACVAAAAHBkbWRkAAACxAAAAIh2dWVkAAADTAAAAIZ2aWV3AAAD1AAAACRsdW1pAAAD+AAAABRtZWFzAAAEDAAAACR0ZWNoAAAEMAAAAAxyVFJDAAAEPAAACAxnVFJDAAAEPAAACAxiVFJDAAAEPAAACAx0ZXh0AAAAAENvcHlyaWdodCAoYykgMTk5OCBIZXdsZXR0LVBhY2thcmQgQ29tcGFueQAAZGVzYwAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z2Rlc2MAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZpZXcAAAAAABOk/gAUXy4AEM8UAAPtzAAEEwsAA1yeAAAAAVhZWiAAAAAAAEwJVgBQAAAAVx/nbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAo8AAAACc2lnIAAAAABDUlQgY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKQAqQCuALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLgAusC9QMAAwsDFgMhAy0DOANDA08DWgNmA3IDfgOKA5YDogOuA7oDxwPTA+AD7AP5BAYEEwQgBC0EOwRIBFUEYwRxBH4EjASaBKgEtgTEBNME4QTwBP4FDQUcBSsFOgVJBVgFZwV3BYYFlgWmBbUFxQXVBeUF9gYGBhYGJwY3BkgGWQZqBnsGjAadBq8GwAbRBuMG9QcHBxkHKwc9B08HYQd0B4YHmQesB78H0gflB/gICwgfCDIIRghaCG4IggiWCKoIvgjSCOcI+wkQCSUJOglPCWQJeQmPCaQJugnPCeUJ+woRCicKPQpUCmoKgQqYCq4KxQrcCvMLCwsiCzkLUQtpC4ALmAuwC8gL4Qv5DBIMKgxDDFwMdQyODKcMwAzZDPMNDQ0mDUANWg10DY4NqQ3DDd4N+A4TDi4OSQ5kDn8Omw62DtIO7g8JDyUPQQ9eD3oPlg+zD88P7BAJECYQQxBhEH4QmxC5ENcQ9RETETERTxFtEYwRqhHJEegSBxImEkUSZBKEEqMSwxLjEwMTIxNDE2MTgxOkE8UT5RQGFCcUSRRqFIsUrRTOFPAVEhU0FVYVeBWbFb0V4BYDFiYWSRZsFo8WshbWFvoXHRdBF2UXiReuF9IX9xgbGEAYZRiKGK8Y1Rj6GSAZRRlrGZEZtxndGgQaKhpRGncanhrFGuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMymzLUMw0zRjN/M7gz8TQrNGU0njTYNRM1TTWHNcI1/TY3NnI2rjbpNyQ3YDecN9c4FDhQOIw4yDkFOUI5fzm8Ofk6Njp0OrI67zstO2s7qjvoPCc8ZTykPOM9Ij1hPaE94D4gPmA+oD7gPyE/YT+iP+JAI0BkQKZA50EpQWpBrEHuQjBCckK1QvdDOkN9Q8BEA0RHRIpEzkUSRVVFmkXeRiJGZ0arRvBHNUd7R8BIBUhLSJFI10kdSWNJqUnwSjdKfUrESwxLU0uaS+JMKkxyTLpNAk1KTZNN3E4lTm5Ot08AT0lPk0/dUCdQcVC7UQZRUFGbUeZSMVJ8UsdTE1NfU6pT9lRCVI9U21UoVXVVwlYPVlxWqVb3V0RXklfgWC9YfVjLWRpZaVm4WgdaVlqmWvVbRVuVW+VcNVyGXNZdJ114XcleGl5sXr1fD19hX7NgBWBXYKpg/GFPYaJh9WJJYpxi8GNDY5dj62RAZJRk6WU9ZZJl52Y9ZpJm6Gc9Z5Nn6Wg/aJZo7GlDaZpp8WpIap9q92tPa6dr/2xXbK9tCG1gbbluEm5rbsRvHm94b9FwK3CGcOBxOnGVcfByS3KmcwFzXXO4dBR0cHTMdSh1hXXhdj52m3b4d1Z3s3gReG54zHkqeYl553pGeqV7BHtje8J8IXyBfOF9QX2hfgF+Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOutCW0nLUTtYq2AbZ5tvC3aLfguFm40blKucK6O7q1uy67p7whvJu9Fb2Pvgq+hL7/v3q/9cBwwOzBZ8Hjwl/C28NYw9TEUcTOxUvFyMZGxsPHQce/yD3IvMk6ybnKOMq3yzbLtsw1zLXNNc21zjbOts83z7jQOdC60TzRvtI/0sHTRNPG1EnUy9VO1dHWVdbY11zX4Nhk2OjZbNnx2nba+9uA3AXcit0Q3ZbeHN6i3ynfr+A24L3hROHM4lPi2+Nj4+vkc+T85YTmDeaW5x/nqegy6LzpRunQ6lvq5etw6/vshu0R7ZzuKO6070DvzPBY8OXxcvH/8ozzGfOn9DT0wvVQ9d72bfb794r4Gfio+Tj5x/pX+uf7d/wH/Jj9Kf26/kv+3P9t////2wCEAAIDAwMEAwQFBQQGBgYGBggIBwcICA0JCgkKCQ0TDA4MDA4MExEUEQ8RFBEeGBUVGB4jHRwdIyolJSo1MjVFRVwBAgMDAwQDBAUFBAYGBgYGCAgHBwgIDQkKCQoJDRMMDgwMDgwTERQRDxEUER4YFRUYHiMdHB0jKiUlKjUyNUVFXP/CABEICO4NGAMBIgACEQEDEQH/xAA5AAAABwEBAQEAAAAAAAAAAAABAgMEBQYHAAgJCgEAAwEBAQEBAQEAAAAAAAAAAAECAwQFBgcICf/aAAwDAQACEAMQAAAApYHH9c4ycfiSjwjKIgMBE4kDmAgvKFGQ3CIhjFAvKABOOAFBQGE5QhPGEVSYKc0mY4UyGMEoOMLCcJ0E4eqO7jNk45hp8qCEzGBSUFiNE5TmFA4jICvAQ3CACPAQTgHAcQTMfgICgAAmAnuESiiIgQx+AoiIcBhBM4mAhwMBRECRETlJiYwJKjwJicwiCcBhynAmPGEU48BDGEZBUKQQVREmY4jIKnDKJhKTOcRJmOIygfhFFQpBTKcBOOoCXH4RDHEZQOcCCpwE5QwicoeWmIqyJgoJCYqC6ROoYhIVBQgKw0ImMdJMTqJo8cwIHULclEwNFE50JGUFUkY4iSBYCU+VBhAVFiXLACQnOCXKiCPKgkmJzNJgqI0RW4hIFgBPlSgHKACYqiCQKgBQV4SYnOUkVYBJlWKCQrACQHUoTBTkiEXByiJxpIicwJCY4IGVODZRUFSXLFJS5cqEyrlYhy5mNjKGBAVQBPlDCR5QRo8qAJlcAJuZU4NhVFtAFuUtxWGmgRwSk3FYCEwUAaYKmBEqwAlxxBIq3AmCnAmC4A35fgbmOYSRXRBogrwJlVEEgW4EiOABAVwBIjgBkBQgiiqBSBj8CYKCNMiwAgKnCQFQpKQLlqSEUKMnL82kVUJEuU6xAxjITKsM0gVYHKYnAEhVKBCOClJkVCpT5QSkwOBRCOCEpGMBKfKiWjyxASKsUgqawAmCxQSKsDSQK8NPleVJFWKCRVyNIgqW0mJxBIFukRMfkyFVBNEFQqUuXIqQ5YWIAsWkQqhRFBUFaYLESIRYtJIxiiII8IhVeGmU4gmCnAnxwBMDgBCqlAhFAEAiUoCqgJLjgBCLkBPhEEgMAiHAwygbiikUAkpDgCZVeJQ4/Eygn7y/pETH4EjiYZOVTEAKcSBVOBPlQEmInEiKoFEBXhIifhJiYwJ8YwiAoYpEFeAhViCIZQoiiYRJmMYZAVAEjG6oKBxdF43IDjjIiKgglypWE5ULknKcIgiZNPlDMSMZQaZVAFwH4CAryExPyRTCLZeEWBxxAgn4CAtwJKDwF5TkEMJ2iAryZDDzOBXkFETMJygEhxxKT45gJwnEQTiMoKcIvKGGmY/KC8oJRDCZtIyhpE+V4SZzGBMVOUlFTlSZzdQnyvGaZlSyFMc9NMVBlJicRF5TikjqGIT5TgDleGmY5hpCqUkgnKIDCIF44AmY5wTE5wbgvwkjHFpIxxQUqwElE4gnx+AnKcCfHESRhG1wH6GmKoEomVC0QxjJp8qCtMTiJPjjUJiqCaXKhSTMcQSMoMUgZXiU+ULbS5XhJlWAEwVK5Lx+STE/CIJjFkKtzEeVByQVOmi8JhoipxJeUAaXKcSmJ+BMFQbKVTnKBz9QnygACavCTE4DTMYwycbhkKoBKRjkJTE5hoFcEJRBZNoAMFBAX5CBjdQmCvAnxxBMVi50kCpGEBYLafKFUp84ICXKhLTMctBAUBSTjirIRUtSUiotJcsEWjygXBOPxaYKEJT5dMSZVABMDiCYqACZjgNuKgOU+XK23OpyE+OVHEUEaQKcJIq4AlynAkCpS0+WTclBYqtMFk3JOONCYj0tMiwWkyrACILEJKJigQFSAUqnDJwmGkVUBEAwDSE/EpGEQT44AQFChwGA0SE4maXGLVFKcyEwVKqSKr1wmBhYUqnZ0QqhHKfH65RE/AmCnDTKqAEEQApFwKQ5YhKZVQEhyvAmVcgycbhJCqQaYG4CJrGBAFxKblXTSIBgaKU3ElDuACqcCHK8VJCYfK+gTOJGCYOK4RAOHjS0wU5QUpxpEETNE45ikgVTABOAi8JiUjGAQcPDDhEoAMBAcfgTMIkl44jTOIAQxhDgNwycfgIPGILx+GmImGUphIDuOCYm4CmE1BeMMhAPzAA5kJifiSGHnQccQT441JDiZsoHEC8fhkMYQIImAgiIAIHmSm7qDcbiiiJkAJ+nMgnEoomC6A3DAQxxoKJ+cEE/B3HHOigYwiCfhlPxgA3GApjHGmYwiJxwJATGEURECioIJmPwEFQ4keUMQQxhGUwnlkExpafKCIoKDcpmN0hSq9QQFOYUwnkIKgITMcblMx+BMFeJTMJgICogkKhgSE4kpCoYpEFBIS5Uw0Tq8NLjGEkZQBlEeGTlBM0+MIEMYB8BhGmJ+qSCfpCAfqCCYQIJhlplUCkQTjQlyoATlOBMTgBOU4CAcSU+UEkgHEpPlOGnypSSArwkhPwycoBZBOAkwU4hLlS2ACgwICsDEgVMCPKAwgnACFVAERUGpSBUBpkU4hMqpQIKhQLxxLSBYBJJuC1KQqCMnKElk5YgkuVAkhFgppmP00UFSlI8txCHLFBMq4MRBwViPLFkJygFIHMDggKBYnynIR5TmIg4CKRKsSpIJuYQqwA3BUAAioAkY/AQqggmCpRkE4pogpzEQU4hPjgMgmMCXHKMhVgEiVQKAIsEhSLcNHlk3SYLpuUwU6kmCnISE4IIVUjQFMZ0jynJpAfnKYKcCYKcCAqcNMFCjJynDTKuQSIqCNvyhXBQNyEwVT0C8cATBUJExOAJGOAJcYzEyOEkEMPIKBuKSA/VKYKcxIFQBIqxUEA/ARNdMEgOLRRAUwIoVUBDkpcU3CQBcokgXKJLlQGlxuFICcfL+iJxuAhwUkIRbiiGEJQcIlBypWkxNyRQEwg4/MT5QLonGFZEExWgE3KiiYEyCoBCZjlpkE/CIJxBPjiSnxxEUFeLT5QoEFThFA4CAqhhJlOIigpwyCYwicoAFEwjSE3WgMboCGMDC8brB4w5hOOIEFUGkxOLReUCbDlCtJnPzCCoZCYK8MgnFIgn6gom6TuMIAI8Ioq8NIxhAvHUYkoJkJgsJKKhzAidQoE5YBEFQ6SZhVGmKnK0jKlcFOJmkjnFCYmOgnHMggmFnCJ5E+VM5S5QSUgN1LlElxBygxRTGMNAVAEQwnBEyoUEMYalNQ4xSJlDOUjKFlkMYQSOI1CZjiCZjCggKiUQFOQjy3VCIqDQQFCjTOU5IcqBSYjxmXjiBOMIE4yhSIqEEAn4RRMYpIFeBMFuBEVeGiC3CSE/AmKoMSMfnKQqABBVCWQDdSTE/NJiJnBBMKsnHBsAOBIJrCNE5hBMqxAIKooQBcBIicWEBQAT4/Ep8qUCgqBSfKcCBjcSmCvMRBXmJgoDlLleYiYwpkA/NpgpwJcoUzKInKIVXikgVKSmKnAioIjIB+GnygAmVUAIVUpmXjiWkVwQEyqlIIVYBo8sINxV4bcxwpJ8p0iBXaNCRlQBIFuGlyvJtgXBpuKoCT5YpZAULUFAx5EQUIMpVi1JAOI0hPwJcfhoCqBKYiYpMFSAUBAAKqQSYKcJIxuAhFgBIqnWJgfnBSmGLIB+YkYRYmVVNCZuNQmYwKkwUByUDiUkChRE4xQJygAQD8CRVTAhygAQqnAnyhQIVYBplWAaArJjKUxhIGMIkQWAlAVABLj8xMVAVIgsAJpOQBuCnNJDxxpkWICXHC5TBckiInCgOEM6AhytE43Wnxjl8j6ABE1BeN0gcbkylVAAEqhYAfgTMJiSgcoAVQCS8YaCCbpCcfjMvDwAPCBRMFhRNwFERYQT8BOOKCcY7Ej9wFEwgTjcBeMIEBQQS5dIngPwiiYRARUAIcRAvHECcY5omJuAgn4ggnERREwcVTiilOJBBPw+4wAUxhKKJhAvKcJMwiIOOIF4xgKCwAHKCBDGEooK8BBOBBR45I8JlZeMLCqAcRSLmlJCY8pM/HaIY5VfCYwE44kFExxpiYwJicRFMYQKJxAAUKIQMJLZRUoirAoBRPxRTCJJOPwF5UQT5QQRMcQJynCDhEZePwEE4gmY3EACgjSOJyUuOIEA4jT5QwJ8pwypOSMS4/E8CgglypakomM6S5QUkjH4ZAWAEzKchMFhQiZTik+V5JIqwUkgP1BBEwJmPwJ8qKEDnFpMqxQTKpzhMTHBPj8BQMZCYn4ExV4EircCBzixIVAQmJuAgKAxMxwYQFeQiVcKlMFAaAqgFE4/DTKpxmThEEuOIJgqUCgY4JFW4aRXBBpccWkeXTqU+UAA4xoaRjlBMT9QlynMSBXiUxP0tMFStp8qAkTH5hOVLNI8qW80zGEpMFCplA4OS8IFEMYAS4/AkJjAUqhAT44iSKoUEzKAAEVEESLkcoC4INMpxYmCxUJAt1JIqwNo8oAkwMIiFUAEyqcCXKFAOU4EQVAEQXKCZVeBIFQaS4/JJicCilUAEhOJSJVuElyhQTKqAiFUNVJcoVNMqxWIgqDhIVCgUqgNkA4DTBQATMfim5lSEJ8JgIJwLKRUASKoUCgYAJxhBExwBIwiCRjcCIqkAhFwBEqwDIismIU1OJRMbhpkWKCRVy1KHLAJMpxYlyvMdibvH+gDjABDH4YFU4CicCiGMYRCn4ZeOBIFOYpMFiiTOIiSE4iTBXhEE4gUqhA4DiBBMAwKoLknH5yBVBkT4w0yCYaRQU5JMVSJkFTqCFU4CcoAi8oAEE/DIVYDMh+OCYnEpMRMIoK8WTjGMyCY4y8AhwmMNMx+Emc5RgJwAonEZBNxAcoJZOMYZDGMZpifgKcxlaZjCIomMpIcRWiYnF5omOICBjSJnMYRFBONIynEEEwiIJzAmY/FlEwgUVOETlOJA5uTIcTCTU4QKJ+QQxurMh+MHGEVYAoCAE4giKnEkE/AQxuaKYwsJynAXjGkKBxAgn6ggKcIvG4O44DDjgAccAKJygAiIiCcCSiYxaQKiSkY3CIJuEmJxAoKcBDGMMvG4tEw8SAjxIcbhgBxLTKoJDcVgpJHHkigbrAEeGHGEEzG4E+PwEMYJCccaSYmEC8cBk4/ATlOJSE3Ek44gTjiWnx+BITcQTjiWkJ+BMqguEDGClxVCpk44ATj9UEHjFplWISmYxgIRYo0+U4SXHAZSLJkJ8oZiQqABSqlQTlAAgHKBOMLlMynK0gVKIgiIE43DICpQS4w3BBMMUnyoFpkVKQiKhdDimECccJCccAS5TkJictiRVikpisUEhUApPlOQkRdNpMFAIAh+bTBQRpcbkJicrlMFOQmRyRiXKBYkKnITBRMfFNzSYqACfKACZT8BCLlBMqpQKCgAmJgEmB+BMeMWQDgCXLANPlCjJxuBIFkiEwOGklKYw0DKghIVCpkBUhaYKdUoifhEExlaRFBBEqpWFKpwJcoUCccQSIqIkTcYCcIFl4xRpgoBBE1CkpAsRwQpwT4DCUmCpSkhMUkgKlJT43A84TeX9CQx+KIBjiJxuJKKgDTMJhFEeAomMUTjgUUDiJITAQHGMBOUACcY4JcoAFA4gQTCBOOIE5ThpioRwQ5xQQFCuQE3AQTCBOUARQP1BQNzZeOYE+McEjmAgnK8NLleEmJwApzcMnKGBMFeGQFSpCJuaADnLIJjATjiBOOIJmMoCfKFSAVOGXjGUE5UAKcRQQTmSKJhAphOJE5xAvKAMpjGFwK8MhhOIgn6JKCnNEExqExOdMnKdNACnWimMCkpjgIDGNIUwimAiYE+VBykoYHICYVRRPyfcfhkMIiLxzAmJzAkZUAS443BDGNDKCgjTEwiSUOLafHFJPlOpJioVyBhNNEA/AQTmYkZTkJCqDCcoVhQOLhMTiUkZTgSMYSCGMYtIFQGmVYDNMxjDTMIlE4xkiFVFiJVgJS5UoiAsWggnFBBNwygJ0JlW4CcYADjGoT5QJCAoAAVQQT5TqEgWAlLlBKKRUoEBQalLlBEkCpQT5ThJCYAT5TnKRVwaS5UBpmMMtExuplIsCETKFclKsBSYKcCZVQEmVYtQQFBGkZQCkgW4EeUKSnynCRMfik+WKmiCybgnKcBeUAonKkGmCnEEEwFlBQBpAqBKIqlYlxxJSBUATBUGJkVLIUDdYHKFBMFSgUw82UhwSICvAkYwptwXLUoCqAJcqUaYm4EwXIJIFOIRFQATKsI24LlaR5UW0BWTYmVwRJPjixIFgBEjgGJgoE0kCnOUyKkaJxhAhT8MpTgBOOIJFXAaIKAJPlABAq5GcA8qIRUguKqUaYKc6T4wJE44CKU/CTBTikgPwImELCicBpCoRiYqEEiKxAKBiBwAYYFMIJFPwkwV4GxjmJTKqQtATEIMRQAS5bk3PKD5f0KJlAb4DlILx+FxTHGmJ+BMwmEQeOCYnAZOOIkhUAghzcUXjcmXj8hIxxppGUACgoAigqUfAfhFBXhInPwE44kJn4SicoBJOMYEwUMxIVAKTFQXKIqChMxhQmZQtAAY6EuVJU8CgyyCYbZOOMohjmlomONSURMUQxjSFA/AQQVqSCIzRRESOE4iTOIgU4iAcqAyGNwuERABMAcYRIDjCrATGWYdx1ZD8dIoiYRROAimEWFMJgKYRQBwUGnyoCTFXgTMcwJmEwFEeAOPwBxhJIYxwKBxGUD8BRE4iGMJRTCYCjxoCgfrCjxQExDi7jcIBEQ4FOEXhMInGECCbgDh4CGPwFE3AHG4CiYwIirwJAqLExMZCZhMCRjAHFU4EwUC0QwmcpCqQCmMIE4/Z0UipLRDGFhAUAlMwmBPlijT5QREKqAEBQQSE5QIJuEUDGEQRMUXjABOOBJBPwEBThpmEQJwmGkVQNJJxwJICgAQR4QFUAafHEEwUAE+UByUQFBQOJSQKBUkERQUp+aIVQGF45XQAp2bIBuYQFeYlx+oJwmkT5QJEwWKxEFyuEjKFYTlOm0gP1ogHMpRFQHaYKlJS43Ep8JQ7hMCYHAEyrACRxMNPjcIhVSUFAw0iAp0NPh6pLxjTSQKEsKJhllTXKJIFC0ilUMmhyxWIipwkyqcNLlAEmCojRBYgkSuEqhMxgAAOEtMVSAQFeLSIsAkSLc4Q5ctCQKFBPlAYUqoAmVYiEuW5iHKACXKACALEApVDDQFXgTA4jSBQo0gW4SRTiSQqoGiRHBCSApxSRFgJRMcKROOKtuR0QSCbktSjy3FJ8qVNIiwgkVQGJgYEiEW6m1BYgimMIycpxapjD5ftJiYQAeGUTjjQmY/JlBTmycsWZKPGYTlABMTi0nygDIcRAnHLJ3H5MnKAUXj9UJmMLCgcSiccSQKfgLygAUFQEkc3CTFThkK4TEXjlEAmEpMwmITBQQTE/El5QSkTHMCXKcHFMIFEwgQTHBMT8Iph4gDCJZBPww4/CSMJiUzn4tM5zEpioJJBMIAJxQUwignKDQQ3KoTMJ1JBMJICJ1QFUOmkJzEpmMYoom4kAOYQcZQaYmEaZj8TxhMUTlOAgnAnuUKBRFQEwWMhMDmbTFQRJGUEaZjgIvKcghxMghzhIQwmBMVBBMVBobA4RclUFYCFX4ERW4SYnFNMxhclAxiiEW5pMVQEmJ+AnKAAcpwJmPwyArwE44pEBTmJmE4ImPwJlW4ExNwJGPwE44XmUFBBMqogkRUrCifgDlBQiZUEycfmyAcrQEWKQTjHBIVgKSBUASFThJCoBIcfi0uUESQqgNLlSEk44DTE/CTBTqRCrcCQKABAVBiPK85S45k0uU5iYKgCQqFBPlgBMqvCR5YoJAqYSHLAxMqxVSQLFJJxzlJFWKJMFBcoirxSZVeTT5TgTKoURQNxBBOU0LxwAnH4EuMLEyqCkQqnDagsW4IdQCkgWK5TKtw0yrACYKANMqoCS5QCUhOAJicRk5Qo0yrFcp8rzaQKCNAT8JMTBKTE3MJxgQUig2kTKkGkY/MKmt0iBV+pNhVTIDjgUmRwUpHj8JLlyDIVUARBYAR5YhKQKlqScoEiYKACYKEApVgdJ8YFRCq85SAxrSInKWmImEiYwAnyhRkBQhIAYRp8cBpApwkOUMJDleGTj8NJNdMCAqUEuWTJDjcUQBONEqpREKoAJlVKxIFiUJ8qCEeW4pXlB8r3khUIAGMKRSqCNIxwYHHBIphEaYnBrinFSmoIjIBhJADHGnxyjKY4EkMJi0xUKIAPwJnMNMnKckUFSkkMPMDjGkKUxqRONwycqDkhVBclAwjAqhgS44CKbjAmcTAkKvFJCYxJDCIJnEQARECGUKQUTCUUTGGQTAT3H4koicCibpoOOCXcfkinMAw4wk8BjDLxxAoqGAh+MBTGEoDcYkoiYkOOYpMFRAgnMIomMmQxhkTOBqCiYXJROKZRMKZOU6ZAREkhjc6Awiq4D8IoiJICYSiiYQT5QQIYwjLyoEkOIgQxhAvGEknH4CqAYC8cQJxjgiKgElMJigKrwJCpwJ8fiE+V6kmJ+QXjmQmJjFJGN1yURNDJyhWE4T2k+PwFE/IT5TmJgqAiFXKkkYx2k+NxZEnHOEDmUBPlAVEETCIVQXKIq86TBUCScfgIJjyIgsI0TH4aQLA5QMoIIictAccrClVAClV6RLjDQUDgJPjiSkKhQKVQAIJyiIJ+BLjhQUFBTSKr1IgKlQQD9QnyhAIY3AlyhRF4xhp8fgT5QATBQAICgiJyhVaYm5yUFCDKVUBJ8fhJkXINMVOBEFQAgKCCQKlBIFAJKBuYUFCjTIuW5SFTkiGAZ0TA5bkvH4RSq8rS5QpKYHFpMD8BQOBZAU4EzCII8fhJgbiCFW4aHLBSRMfkEKoCClU4CcpxSaaxKhMFC1CYn4aZVeKSBYqaYHBifKcCIqACYKACQKcCXHAzSA/AQqhhocoAkuU4EhExaQLFGkCpXKYKg5SBQ1CHKCCAKcCQLFBPlBWiBlCsS5TgQBcoiAqUaQK8CRViACa3AiVykCYKgCfGEEgVAbYF+JTKsQpPj8CfH4avcPl+8AHECccxSfKcSQT8MoHESYqABCrASTjGGUTAAcbiA44lpiqQCmOIkxMYtPlAAgmESYn4CGNwiiIjIVQxKYqFGBVQJKB+EXlSgTlk3BBPwEMJqSfKCBOPyE+V5iYnBsnK9KKbhAgn6ghjcsw4xkF43LQDHK0HH5wQx+QU/GQQTCgOE4E5QQIYTlEBXiCGOYCCYwyGMIBxhAphONMTmEUTCHccYC8pyCHE1ACbpAEwgiYTAQ4nJIJjFEMoUCifgLxxJIYxhkExiiCYwkxUERRMIEBXhFEwiIc3DDjCUXj8SAiaGQFOuCGPwyGP00TlStEE/OU+OAuNxxlE/AmKggjyoEJmMYaQqlEUVOKLxhGmJhJIJgJADcwvKFQmYwUuBTkyccyE+MIEKqWggqcxFQ3MICpREFThp8pwJCcRJCfiUzH4aJlDAmCvDS5UoABuGTjgSUFAJTE/AmRYAICnAnx+YQpwQXjmsSBUGEBThJ8fhpgqURAV4lPjgWnygEJCcBE4/AQFOBPjgBQMIJGMDEwVCwhViyE5QtBQUCWQi4CTKqWgonCBPlCtkBYrE+UK0XjABOPwEBUoJgfgIVTgT5QASE3AmVURIArwkuU4pPjgJMFeaRBYjEuUFhOP0UQqxAKRQKCAoAilVBNPlSsT44sT4woSBUqCFUC0UihREE5SS8cAKU4FFEeAqS5XKYKgJIT8NMD8whVSAQqwMSE5pEOPwIicWJlUMhvygWkQWKggHBtMFigjy6YkwOUQCPDTKsAkwPxKXHACApwJFWKBQUKaFIoYSPH4aQn4EuPwJlUFjcVSMTBXmJAoCCFVAEePwEBQoJ8YG0zDwJgoDafKcCXDwzHUDy/fKBhJDj8UQTCCJzGJKJgAgn4CgcADjARwiJSZhEXCbiiAsUCiYyCG7noXj8QXjCIoKgBBMYaYmERQMIAPGBMVAEXjcSUTlEny4CSE4CADiNMVOJT5QxSfKcCZVBcE5QVSZji5SOcEF4TATlDGaQqCUXjCMnKcIBOJROU4RRESA4TgQ4GQAn4lNUDgUxhVF4TsAeMjuNyCicWEPxlIGNyrjAcCG4AEeEAOJhgPGGUTGETj8Mp+MSUTCMOPwEEwiKcqhRAOYAMBkiqAZIAULQBuFHCYYC8oFoon5MhhGTuESe4wjLxhGURMBeEQKCgNJAr1wChFZOKoEheMIE45rSIqAwvHKAgoI0xPwF4wAXj8SQTCIvKAMgKcSTj8BQUAZBMYCAcSicbiSCcRJCoVhBOCCcfrCccWFIqIJ8fgJx+AoHAAA4AQROJMqoEpiJhJgcQKCnFJArwJAsUlIVQBPjCCYKFaKU4sTMYaCcY0NMqgAlxwtE45SA4RAnH4tLlCkFKoIEA4DKCgDS5QCSccRkKoAJmHhE44ATjiCJhFhQNyohVSklKoGglygAmKhAAqoAlyhkIioCpIq6blMFBaTExppEFC0icoUE+PwE43AVNYAR5XgQUNwEKoAJgoIkwU4aXKlACm4aRhMBAOAJlVByiJuqSFUASYnK6KPGAgH5NPlOGQh+cpCfiSgfi0wUAhMFSlpgqBKJjcJMqggiJxGnx+BEi4CR44WE5TgSKoAFTXKJDnBWkiqcNPlOTRBYjSQnARAUKIoH4pIFeEjyoFEKqUSQKcJMFOKSA4AUhhBPjiCZTKDQBQRJAoQCAqAIkXTpcU/S0iqkpE5Tk0uNyFR43mfSEHjWg4/JlIqLhMTCJPlBAgKABeUKBRMIicoABxhAAOIyccA7jcBD8aQoKAgonLQXjgwSmMgAP0hDGFynx+clEwyycfrQAfgKCgoTKsCCcc7EeU5wUDiMgqChEVQck5TgIB+EQVAIKIiMihyiARArhUFMnKA5ATiIoiI0+W4RBP0sOP00HH4gDHECCoBaZziQQxjATjiBRMYA4TFBxhAhjCJITCIp+OXwiI+4TEFMJkyGE0shx4gBEyoBNxRBMNhRMMogqCpIJ+EUTGAvH6gpxNIUTAACfgKJ+AvH4C8pxKZzCMvCoNI/GEURMMvGMCQLcZkMYQJxjAnynAXjlAOOLEwVJS7j8gomNLTAx6EuV6kkc/SJiYaafKAZgBylEE4kk5QAKCnDICnCKB+DinACArwJcpwJioLEwV5BCLA0nx+bKBxBIVOBMTgBOOJCQKgIgKhQXjjNJcqUpMFerNLjCNPlQKTBUpKQmESfHAAA3AXjgCQmFiJj8SlygUicYHZAVKQQVAKTBUAIVUok+UAkgKAUQFAJJygFEBUBpCoQCCoI0QWKQkCqbkCq82mKnJpFVKkTlABMFeGmChSipuCOUeV5pEVCoT5QKCAqVCYKFoKCgoRE5WAU/ATjgBCK8CRVeEmJuApV0pZAVBifHBhANwJicokyqGcpcrxaQLFSSKqFSnx+aKVQFaYmLUFBQAT5QoEA/AUDcWnwiQQDgCQnAZePxafHKZlBQo0yrA5SE/KkyrEaSBYLhMpxi0uWKxMDmkTBTgQ5UKEiLABCqdImVUgJiYNAgKckjyoJpAoVhCqgxMFCgTjgBeOGYmm4JYQFCMAD8U3FUBIifgRE4jQ44jR5XhAPH8z6IvCKCiIVPGEyZDiCReUGmiJ+EQTi5SN3B3CdUmYRJ7hFBeMKoph4ROUARTCIycfmi8cQTMfky8oIJcpwiCbiUxOIiGODZSnOkXhERAVAZQUARQV4SRjmBPlOAvccRAVKSUFQpEMYCOHhQTlBaIYVE0zCZBBOYpI5hGTlQpEMIzICIjDlOKJyh1JOUFoon4sgmMIgnERDiMhRMKRDiJRTCZ0UREC8cREMcUFBTgKJjJFMbhhxuGICYkphEkBETQpjiZpmEwymMAcJ+EXlOKKJhEUVAQQxxaLxjAXj8BRPwF4/AQTcAAoAu7jEBxjrQgjwg4xnAcYSycYSCcoAF4wgUFAAoiBICIjARMNIxgEUR60An5UTj9Uk44ElEwAHCYZBN0onGGgAPwJmMI0uUKSHCIFEwjII8BQOABxjAmC3AkJgAoKCBOOAE45RFBUAS44iJx+KIJhBMqgCADiNHlAuCFVK0nxxEkJ+GmBwAnH4CcfgTE4AQqgCT44aQXjCmQFBVpcfpEuVCwhVSKSCYKkAPxZOOAyCbhI8pylM/GdEKoAyFVKSnynAlyhSSgcBk44CKBxGkVYpRSLFEkCnEpgcQTKoDCcqVUmCgElKcAKVQGFKoLEQVLQQTABQUBMpTjAmVQKRAUAafH6kmCnAiCpQIJyiDh4YJq8NNNUCUjDxBAUEtMDgMhVAEQTdYlx+BMTdInxjAQqgDKVUqE+HhJlWC4LxwNE+MDknG4SYnKInKAUkCgEgVVMZAU4SfKFGmCoCSBQoEKqVohVuGhx+QQDABCqCCAnECJLkAhVS2AmsmgAUCRMiwU0gP1JMD8CfGAClUKBOULIUBLVdxuKAq3eX9AnynEcBzFonNxJRNwg44F8RcgEE4iR4/EAJjFEA4ElETAQT8BDccCCIgUTcMvHARimECiIgUREReUKMvKiJMFADiKcIhh4nh4QLynAQDiSQTCBOOIigoYpIFBIIBjAmJzAnxzAmJhJTFUBEExxFEwlF4/DKYTCTFTiSiYxRBOIFNwgAmMUUDCSUTGQHCYophNImYxkJmPwiifh9wiBROIyCYRAYRAAMIFNxwKYRAhzcBTGMBRMIENxiCnMJRBPwFMJhkE/JFMcssBMKzAROwhh4CHEbAEeQAiZhB4xJTjxRRE8ykJuqQMYC+E3CKbjAA8YCCYSkwUAzDh4A5QAKRQRFE4gQw8NMxwAhlAYQVAQnyoUiccZE+VBpIxjUkxOKpEVOcJibkF5QrCAsDSXKgCZhEafKlBMTgIpxEaQmEkCqAUXjCBOOAEKrwk+OAF4wgmJwEQVAKJx+AgKFEmCgkJlVLTT44tJgqDCFW6RLlC0JicAJxwBMFAJICnEpCqUogmMUlxwBPlCtEE/NkIsUkgKlAgKlGnyhqlLjmztHjGpJ8cZaSa5HJAUCklygNJ8rypAVRBHlOVJ8oDEiqlckKsCE+VKNATi4SE5QLxwGkCoCTKsBSRjgJIFitpCoDSfH5JLlOTT5QtMgKlEkJwaICgQJgoXQIVXgS44CJx+GmChSUxMIEKoJSIKAIgKAMgiIJlWAEeVKBBEQJxwBMFABMD8JMTgNPjg0nygOSccrCgcAKA9NEA43KYKAhIVOTSBQKSZVTAgYwgiCpREKqUEuMYEQVIBQVIBSKCCILkBHlgBAFwBEFSgQipQT45QJyoMSKpwI8qWpTKsVUmVUqovKcpDjG8/6QnH4AHjElA4gmcRGHCIAJuKKBhMy8YRk4xhp8YxCYnACifgTMYQLxjDIB+EAH4CmHg43CgomFInG6mHGGYLynISFQzSfKcBeE8iJliAQVAqClW4tMFBIIImQmKgNl5QtJM5xEQTcgoiYCCfgIYwsIYwoDj8BSqCwomFACPI4D8ACJpRRMLYAczZeMaWQw8TxhAZTiIBx+ApuOIhuMADxyi8YRFE3C7jCBDGEfcY0oomMBDCMhTCLCmN1IBEZZTGFhRMaQgqcInHEZTcYCmMJIAYwyCfmi8pykgmEA4TgBVDFJcoJCQqCSkoY40uOYExOYaZjcMvKACYn55pGUChMxjgmCoILyoJlKqFInKcHFUBUUqvVJOPwFBTgJygglynAQTCBANwABxAhVBEkKgNJgoWpIYwgTlOAgKchMVOQnygILx+bTE/OkTH6pTE4SkwV6hPlABMTgInGECAfhlKcRJgoUgOUAtMFeEkCnOSAcUJgsD0QMcQQ5YrzSBUKEwVKBAWACccAKVXgR5UCUxMYpIi5QJxwBIynAlyhQTMYQR5YBJccRplWAEyLFEmCwAmChQADgCYiYaQnASZVC1KfHMUQqpZaZVAqEgUCkUTcUkCgElBQponyhSCccRplU4EROIJcpwkynK1xFAVJKEUBMojpKfKhATlAQkCoUJAp1CQLFJSE4KiCcEJApzEiqi5Q5ThJifikuVKNIxjCSKtwIcrw0irEJTNxgTKrwJCcBpGERIgsUE+WKxMFCplKcGgKYXSYKFcE4wNFERiiAqQCEW5pEThQRNYBIgsUCAcgFKsUCcIgQFOVIEV5ykVTgSBTgJwmBMDcBCqACQmMCZVCjT4/CAFO8/6NMVAGUTCIgnGUAH6qTMcQLxjIT4woKCpWFBTgKBzKExPwJcoYafKgInH6WBFTsRFYrognGcyAqAgA5hkBQWkzHFBBVKpTFTmk+VEExNwABxEmVURJ8rxRCrcJMTHEiJxJJyvDSMYQJyvFJicxCRhOIhjCMgmECCYQICvCIYRGUTCBRPwymNwiGMIFE4C4TcMAU4CicQIcTIIChlSZjGqSCYyaYqCkQRPQQRMBeMZBTiKCiYUcB+QU4iBDH4CnAwAJhBMxjAXjCSAiYQccCgMbgKY3ElExxEEwlhx+TAFOEXjc5ATcBTCIi8pwENxhF5ThkE3AUwmAnH4SfG4gDDw+43AQTGEQVOGiYxhEEwgQFAAomMCQqBYTlAaATgmnyhhIifmJgrxKYqAqIC5RpAtzSPHAgnKgBQU5hOEwEE4oSExgIChQADgCfHEEwPzknKBYURNnROMIJArzEuVBifKBQlypRJicFJQUESPKi6TFQqaYHFtLleBIjghKYKgSgKxaExOKEgUEEuOFBOMYExPyEyqcCXLAxAVeQiC4NICqI0OWKCQnFiYHEEQWAEeUEEQWKSmCwAmVUQRBTgTKqUlPjiUmChSkyLFeZOWKUnyoKkeVBiXKAhIFA0SfKApIChSyccHmmCgIS5cgJ8oDEyqcCYHEEwVKBAPwJ8oAJgoAJlVKInGEaYKACQqA0mCoJo8sWhIThQmJygTjmSS44JkA4UJ8fgTBYoEA/AmCgAkCnCS5QpJONw0+PwkuMI0wPzpPjc8ykVCWQp+EBVAKTMPFJ8cBEKpwEKfhJ8fhJgqQEim7RF4/ITBQrEwVCWlyybEwPzSfKFQkVYrCcPAUphBLj8SAn7zvpUzCZJM3HlkEwjATcBeOYaYnERANwE44MAwHEQTCpDjAMCnEABQoigpxmQxhLJxwApjcQBjcWQTHEmIiQHGEABQJC8p1BREQIJhkLx+oJxxEQVCJgCggmJhclBUCi8YwiCYREBQCSiYQLxuADCIEE3AAm4CmHgKJhAhxMBePxoUxuMyGPwFETAXjiBDCYE1BNARQRQQROwhjCghhMBRPwEFQoAJhoARPImYTgQ4iBePwBxjgQw8ACJwLx+AomMBDCYRROIy8YwFHjCDhOSQTigOOKsom5ACIkl4w1KZj8SUwnLKAi2QxxiAKpzZDGECCY0ifH65IJ+cpgtwIiqIJ8pwDxwLJxxEmCoiTBXhJGPwAVXgT44sAD8CfGMIgn4afHGkQT9FE5UoI8ftISE/DLynIRFUSEeVFtAygglypRFKsQC8oYaXKCmgKxXKBliAkZUASE4gQVABMqvAkCggjywsRBbkI8sAIipwI8r1CPLACRVysSBXnCPKcBSqcNMT8NMFSiS44EkFTgS5USkAVAkhVAAnHAC8cRp8pxSQKgCJV+cIguViXKcCZViAmCxQTBbkICoFCALFaTKuAkTH5UnynISKqNJIqxRkKqUEhUAEeVASQLFbT5QEJlUChLliuUuOZNIFOBHlApJgoUlPlOAhVSjIVThJiYBpgqUSZFwbR4/JFBUAIVUgEE5RlA/AlyxBJioDaYKFST43WE4wQigpw0wUKBQUAEwP1CXKFoIVQBE44DTA/AmBxAhVABMqnEJ8pxSYHAAKoQZQEQTA4gnygCAigDTBUhJAU4EirANMFQBITCNETABAUAEeOURCqiCIKBUpcqVBCLlGjynOS8YfN+kIJhEmY4gQTCNMxxAeHiigoVSTlBYkCogkCvEkE3ElMYQJxxQTlDobGV6pLxxVJifkFE/MJyoITMYQKBxWZRMKogqcCYnMJLluGThEkonKUBhMSTjCBOUBiYn5heP1BQU4RQU5IoKchMxxoT44iIJ+EQxxkT5QWEBQypMTg0HH5oBN06EExyAERVAJhSJxxJTMY7EziKYcfigMJiC8oAAJuGBhEsvGEkhjATwmMMvH4QCbgHuMACbgAROBQMYA4wgAieQgm4AETMKbjoLynCKJuEUTHmiGMIEMYQTMYTMOEwFEwgXjiCfH6zhE0WnxzEEMcAKJhBMxxoSMYUE4/Wg4RGTjiBBOKROOZtPjGBExzEIHMIE4wiJyggUFOKT4w1JeMMhONwAPGGTjCJID8woK8BAUFCQqAIoKdTJypZCccAIBzaIoKlhp8pwkxMJJOPxSQqA0iZUtJPjiJMxuLJxxElx+EnygCIJgBIx+BMFOAgKANITiJJNz1JtyoVKYmMUnxuBMTCNMFQEkKgDTEwCIVQpBOVAaXLFBPlSiTE/FJ8oA0RVKSTj8JMFOBIFeBDlysSBXk0yqgJIq3UI8pzEeVBBCqACQnLQBVSglyxQR5YoJCoAJAsUEiqgJLlSgkKgDIChRJgcLkoGAZQUI5Lxxm0eUESQKgNLjdQlyhSClUACAYwyEXTGQFAJSBbgSBQBEKqUZQUAE+UKBAUKwnH5CYjwEKcQTBQAIU/AlyhaknKA2mCnJplVASILJsAD8ggKBLTBUrEwU5hCKBUFA3FFA/DSBUAT44IKVQEJgrwIiYWJgoDE+OAEBQshCK9SbmVKCRVeGkVcARKsQClPxCfKcIgiPnfUF45pCCIsJxxaKBjOA4/ZhROUCGEQLxwApjcBSqGIIJgEXlRKTFQgi8qIkVTABQUACGNwimEwyApwJicxKfKcJM5hLII8SHH4ZeMIi8YSim44k+MJJeMYCccQS5UBFA/AHGEC8YQTMcGEMcQJxzJJCcQIIiSUTCWXj84IJxEURMgomOMhhEsAUKTwjwinNwgETFFExgIYDkgbjARQRKDuOUUTcBTG4ANx1BRE8sgHFIvKCwnKCkURFhDGMwomFBTCZAccwE45gTMYRgCojIInITMbhgIiHcYA4FOJIJjElA5xkFQBpiYxJDjwym5QSYn4C8YwEExgTE/AmCwOCGMKovKAMoKcBDG4kgmM6TERpFKoDZSqcQUT9KJxxoJygATlBBMTiCXKcCYLFBMFAAnLAJMTcMvKgBeUKBAV4EuV4CApwE4/AnygATlCgXj8BOOAiAoIJAoLEuUC4ICoAkYwgmCpQJx+BIT8CYnEEwVApMqoElKoAJccCSgoVhBOFyQD9NkEwppibkEIsSpTFTqEzHCKTBTkkRU7QTBTk0hMIJiYJEyLg0kCgVJAOAigqC0SBUpCYnBohVQKIBygTjiJEFSiTE4AkJwAhFisT4/MT45aClNyE+ODRSKkAoKcCZFCiLxwJT4xi0wMBPFMBRQNw0wPzSYm5shFQYmVUrghuPLTKqVtMivEonNwFKuSWlw9c8RQpRCqcIpVASSA/MIAiBBOJSYHAE+OAkyqlETjAAEU4E+MAFAxQLxgACnEEwMAgKcBkBTmJAqDSfKBLTA/AQp+BPjdUBxwnVMRKSUqgAUqgNlARSTAwsTEwATlCoIVQAT43UJcoIkeU4aZVg836MoKCIgKcUTlAJTUERkMYSUxMYEjH5oBOKE+MIk+UOSkY3CKImGXjCMvGMpTExkInP1BDcZBQUBAAfmF4wNcBhRwHBMgn6gOMKC8fgIJxQmJxAnKcBBEUF4/MTMcCSjx6RQMIgA/IIJgDuEzCGNwymERFEwoLxjNJ8YSSmExRBOYRR4wF44lEMJgIJjAURGQomGjiqcSU3HUlMB5OHhWgG4xJDm6qKJjAHGGUHGMIgnEkoiYZRExZRExmUwiACYQAFeAhhMMvHERTCYCiIgAiZBDHAA4/M7jCBeOIJ8qBmUxhl9w8WUwmeZeU4aZz80UTdDJxzCIPHoKBzoRMoDCmNwJioDCiIgXlOApVQBLlOMy8cSyAfgTMIiIJ+c8IitEhPzzApwAgn5hQOLEuVFMhHBU0hU5yTlAYQD8wgnEE+OZCQKAwnHMCfGEE+OIEKsCEuU5wlyolJAoIkgUElEVBGjygCJynAlynWJlVFCIqABCrACfHACgcAT5QwIAuShMVQBIFQElyoDTBThE4/DIVTgSFQARMcAT44EkA/NEEwKykXI0mJwQUqgDRFULlIFAcp8qCEwU56ImULIQi3Ajx+qUgV4ESq8SkCpQICgFE4/EpEWICfKBQkCggmmuURCn6kkJ+EiCxRkBUBJFV4E+UApMD8MgKACQnEEgUKBCqlBMFQIImrxSXKAMnGECkVKBCLFcpcoBKQqAMgKAkmRYGIGULQmI8wCqArTBQpJCqg0kJxlpAcwIgp1JMqvIS5QoEA4MLw8BAUAE+PwJgcAIB+ACnAZAUCWlx+pEA4FkKoBJAPwiFUKMpTCSQDGBIFCgQTcBONwyCbiylVASfH5SkBzef9GQqvNJ8oA0lFAkT4/IKcw2EMoMohVQUJipyExULSKJ+UJmODEzGERREUwHgRw8IEE3U+AwyF4wiJynMTExmJmNyCicAIY3AUw8gph4CmMAAJuAomECCcQTMYAKJxBPj8IoiYafKAZpmNzCCcaCmExROPyRDG6kUTcBROIiiYZAERmCHMDZTcZ2Xj9IU/GYQwmQAHECmNwFMIiDjGGQxjAQ4CIREQATCmURM4TV4RgImGQxhQUTGbJxxIKYTCKYTAXjGBMxjAHG4CnE0hDGECmN0hTGEExUBgccWFEwyFE/AQ5gAOMJJFAFopzCUXjCkQT8SQ/GK4FOBM48BeVACAp1STjignHCzjCMohVhGiKnAQTcCfKdUImU4SZzHVIgqVogmESZjGBIynAnyvDTFTi0+WKJLlikp8qDSfKCxPj8CYnACFVFhBMMCQj1BBMMhBOAE5TgSFQKEwV4EwWAEwVBiRVwcoctwkuVASfKcUQFAKSE/EoioBKfKACZjcBAPwyAr1WjygGaYK9QkCnAiKnAlyoAmCgAQqwy0BV5pHlAYnx+AnGMNAVCCT4/EJgoBZAV4EQWISQFeGmRUBkBTmI8qS5JygQ0yqlpplV5ykC5CkwV4lEqvKUBVApIFAcpAoUExNxJOPxSIKlaIVQU0yqgwgKFoTBQGkxOMtIFCyE44WJifoaZFU6kgKkqOA/GiIKgSnynFJgcoilVKSTj8UmRTiE+NwF43FIlW4SIn4SYKcCQKgUThEaYH4Cl4wFIsUaZVQqUyqASQigMIJgYTjABSKggoH5UnxgaIBwSKU/UEA4SEBUCkhNwJAqFCYKACYnBIoKdLS5QRpFUCkUD8MgiMMvG4ERVDz/oicYxJCrgCILkEQTnAnKC4IY3IKVQQKBxQmBxeZOOIJicAAD8MgmMBAOIigpxSYqCgnG5gcbgTMcSUxNwFE/FEE/El4wgQxuAgm4OE3DIJuEAnACm4xROOJKZj8BREQJx+AnH4CCoUnuNwwHhDgOIygcTMgmECCIh3G4RDG4nhHg7uMWPG4AEwgQw8AH4QAw8ACYQKY3CA3GGHGMSU/GAAOJRTHAkoiYA4woEFQKJxjtFHlFCYnGWUxhQUVOAAUEaYn5opjCgBMYRBESgEQKHhEz4TcSUxhK4qnDTOPCDj8MpjGITOcRp8oBIcYwiccwy8fgIJ+AonEEhU4SZjgBRE4J8fgAREaQqFEHH4CFVFiYnFogn6WkKo0kQVFpPlBTICnUyCYUEAwgAKA0UqgglyxSScoBSYLAQmCoATj8CYnMNIFeBEVeEkCvAQFCgBVRBMFOBPlAAvGEEuWKCRVQqUgVCpJxhKIB+BMqoEkBUBk45y0SrACYnAEwWKCfH4SYLACQKgJLlQBLjgSQFQGQFALT44maYKg2iY4iRE4IIVYtNHlgEjyggmCoKkeXAEgULUkBQrEhVAEhPyEiLAxMioAmVYgE5UoJgqViYKlQQqpQTKqDlIFSUkxUKkQFAoS5QBplWKJIFeBLjlAoKAwvGBUmCgiQ5YBIgpwJApwI8p1JLjgBOODCgItpFWKBCq8CXHESIKlETjCUmBwAgKgCXKcJIFijSMcoJAoAJgoAkhOAk+OBRQOQRQOUgvGACAcRocqW0QTDNJFV5NHlSklKoJSPKCCQLFGlygAnyhQTBUoJiIgmJ+BMTlApVOBMqgEkA/FEEwATlOAhuHy/oCm4akBHki8pyEjHFheOVsAMNQUTdEl4wAXjjaIbhmi8bqRRMKExMDYCYCeEDRpwCKgvG5oOMNMvCZonGEZeNwymMAcBuGHGEgoiYC8bhlE/JEMbkcBxlkOIDDhEReP1pMVOQmJxYnxjMICgiTMPE8YRLJygkpGOUkpxMIonEZBMIE44gURMBOVAOEwjLx+EAiYEzmECGHiQMYSimNwuE4wiGMLZRMMsomOIhjcMonEA4xwSOJiS8Y4yipxReOIiiYwEMfgLxjAmYxwTE4mZTcebR5QGyHE7z7lOApj8qLxxTKBxTIKgOCmPwFET0kwV6ZTMcQTMcRpmMYExOIFERaIY3JJmOZtAVTMS5bpaXKDSIBzAkKnAkY3ElMPAmcwgnxxBIVQAnHMCYK8CYLFAvH4CgpzEhUFiQqFAgn5CYnEEwVACcpzEhOAkzGNSTBYk0TlOBIVArMoHMNHlQAgGOJAygFJgfhJgoBJSqgNHli1KQqAmQqwDSFTmiAoVsgKchMFitJCoVtPliiIVQBEE4DTKsI0SrgJHlgElyoDSBURpcsWRLliNJgtzSIKgUkVUCUuUESYKgmlygOkirc5Q5YoiFU5NIFeEmVQGkgOahHlOQkVUKEhMKEyLFBMFBYkRYoJAqUSfKCCILANExysS5UokeVChMqpSSArwkeV4pEVAmkyLFqUwVBygKvDQK4KCJVykpFVAEjmEEgWAaHKgxHleQiRYtSXjCqTKsmBeNyEwOGgUDhAnx+AhD8xMDihIqoOUwOFUQqpCCCbhJlUKBBMI0yq8WQqhRJgqAEBTkycoENMDl0QAYZEgVJSIIimkU4tEBUoycfgIB+BPjghLlOBIVCDJx+SJynFJGN3m+6UTcSTjmEQ/cWAiIy8cAIKnEEA/EF4/DKBuJJygMLxhaLxjSyCcCiFVI5IJ+VCIiSUeOWQDiIvGMJPjmAgKcInH4ZRMAgBQREE4AU3CBTcYCGOUO4TAQ5uAnHEC8YADj8AccAJxjUE4/AXjCBRMIF44iTE/VAFOIcYDAUwHAgiYAERDuMdBBE6sgn4gvHECiYyCCYWFExgATDIRQDgXjCBTGECHEwAInGUTGEQTcAGEQKc4gmYxgIJxkIYwsKYRkIY4sIYwyF44gUxgAoKi5TOJkyipw0xUElMxxGQTcAcfiAExhk4wiKJjAkcwgXjmBPjiInGEYCbgKJgAONzB44I4D8CZh5heOLROPwJgqLhMFRbSMYRoisQkOU4EhOIE5QypIFStEE5hJCpwE4/AQFignyxQIIiBAOIJ8pwJgsQSZlBbS5QEAVQgcURAgqc0kCpakgnESYKc2lyoCSBXkJ8sQEyrAxLlBBIFhBDleBIqwgiC5ATBYATBXgSBQQQ5URICoYaPKCCXKlBMFgGkC5AIVcGIgqCSYK8CXKCCJV+BuC4UkuUFNEqxUkuVTpkKsFSmCnIRBXmiFUAEwWApEFyCTKqURCqgJIFQBLjgCYKFoKVUtBSqlBMFeQlyhUJFcEYlyoMSK4TQjyosQBYCETHMUmVUo0yqkAgKFIT4wsIRYiZSq8NAFSXJQWKNLlAmiEWBpIFS0kiLFJTE3AQqnAicxQT5QgEFQAIBwKIVUAImumIhVSiS4/AmCwDTKsUSYKACIm4CAoFJIFOqUxMM2kJ+kIBwLIVQHCfH5BCnKAFWICYKhQQiwJpgpwiAfkJgoUZeOBaYKABOUAE+PwImIPn+2cwBIIiLZTcLCGHiAA4jIY3SwA/CIJhaTE/AQxhmkwVB5k4/UygfgLx+BMT8AcIgUTcBDiAcIiBRHg7hGQvG6kTlAGUT8JMTiMvG4RBOIiCbgKJxGUREYcYVKYKgSAmF2QTgIgn4kom4CGMYSYnEZOOAiGN2kFETTRRPyRFCqCIIijhN1ACJpAHjABhECiIgBh4AMJgIKgBwmERRMIwE5gSMoIJmMYCicRlE5pRBMIBxjgQTDIURMwBEyA4TiLxxGUxhGQxjAmKhwRMfhF45hE5QQIY4jTMYwJiYREE5gT5TkBxhcAJhVE5QGAbjgmbjpk44qEjGGgvKcBRMJSYn4kBMYpMTASQwiAcYwJCoURBMIiFU4RRMJaYmNWaYqdNpCpwiibhk5QKgoKBIQRNYTjcwOEQKBzAmJhGlygCICnAHGEE+NwF4/AgRdKWmcDhxhPSTE3CTMYRpcpwJgoBmmZQpSYnAZOOFwmJhkSE4AQTCCYKFYBFOYTjCxPlOBHlABMxhBMDgCfKFAAUAA4xSi8fgICgCTBThJlU4EwU4E+UKBSqlBLjgSQFAKSKuAICpwJcoUCAqUSIn7RJcpyaXHBiZVCkkBUgkxMAEKqUCAqAJcoAEBXikiqcJMFAEmVYGIlXIwoKAhMFiMS5QKEhPwiFUAaZFBJTIuQaIqcCRFygmKhBpAqBJSn4pMDgCYKlcJgqAJFXTpJgpzEgVLIkJ+oT44FFKqVCfHBymCoDTA4AmCgCSFYBocfhEKqAJcqUEOVAhIqvMS5TikuVKmmc4jQBQAT5QBJkV4EgUKBBPwJHEyspFAmkeVC5TBQqkoKc7TKqAJ8qWQhFQYTh4G/Kd5vtkKoIyqFVEQwi0Q/GVFA/KSHMIycfhk5TnBBNwkz8ZUTlOJIBwYQ3GoIIjIHHBAcJmEEeYHGECiI0F4RR3CMgAYzExODAAxmiAcwyGHgKbhAomGZKJgJA3GbKJuiuKcGgEes7jCUQxuWZSnFhREwF44AXjCSAmEkvG4O4TAQwmAvHERRMIw4xgKIgBuEwFMBxgIiIDDwcImAom4njCYCm45QCIwAYRAB44+4wJcYRGU/cLjDwBxhADGMBRERBwnApjCCZ+OAcY0somECiYwiCfmFMYZZQOKC8pzRBUBopjdNEMJjNMxhAAPwwHjCIYTMLxgQAmFhQPzCiI0FOJpC8Ipl4/WkxMYC8IgBFBEQDiBBU4afKCJIT8SQT8InH4ZeMIE4xhJiYQICg1SJlCiDjikmImAvCZNIxhaSE4gQFRTQMfqSYKCCRHHA35wEiQKhcpHOAEMYzpIDgJMFgITBbhog4AaPKCCXKcUkJwEnygCS5XiUgUEaQHGkQFOkS5UGJCcWImMYEuUBBCrAUkCvEo8qDCAsWaSE4kogrwJcqDaQLpsT5TqSRVSgQFQBIFQBHlABMqwAkCoAkJuBMTgCRVQYmVQKzTKsCEgVChIFDDRKsAkuVKNPjiNEqxSUjKghIFQdp8fhpAqUE+VKZpAqAJlV4EgWAaRVysRKuVJMqxXSILFcpAfgT5QARFQKEirApSBXnSXHAEyrJiRMbhEBQCkgV4SQKlEmKhSkyq80hynMTIrwJ8YZaZVAqUgU6pICnRomVUFKXHGpRK4KqR5QGJAuQSfKlVFA3IS441KQLFVJcqQQEXTdJgcWARQsMvGAROOAJgqAJAqQQccBplUEE+U4EAE3n+2QqwggofgLx+GUTcIOPwyiYQJxuABEQTMIkkMYCQ4TAmJuAvG4C8cAIY3AXjgBeOIFMBiiccWicYRBxgQBjAHcbgIJuAom4C8YWABjoJxhAgqCInCYRRNxRRMAgE/AXjDTLxucEE4tFMfpZBMKSYn5pM5waKYxmkxEwi8YwEETB3CYZTG4sphEkgqcIoiIuETgA8YCmEyAEwgU3GgKcwBxuEOMJgKcTDKImLKJjIIVQVHDygEMcwkzGFBDHFhDCZBDiKC9yrZDmMkQVANCiYTNMqpQBQDBwnECCY40jG4ReUEExUARBPxJOV4sgmMJI5hAvG4CgoJJOOIkxMIFMcSiCPFBxhApVBcEE3Ui8pyE+U6gg8IcPcBTDwJ8oJBQU4aYn4aYq8hMVATT5QKCGEREFQoi8pwJCcwJgpwkxU4onKcNMFAM0zmAEzH4ZCrcCInARQPwJ8cWkxMdtHlAQUqgITE4MTBTrE+McEgOIJ8oAEKqUCAoAEBQAKVcBImPwJiYwJFU4E+U4aQLFISFThJGNxRAPxRAMJBOMYaPH4ohFeBHliVKQqFST4/JJgpwJFV6xEFuBIi3Mb8qAJcsVCIn5iZVwmkAWLUpFWASQLlYkVYEkgV6hHlSyk+OA0+OII8pzRAU52lynSJApzSQH5ymCnATjhVpkWISnygCTKqUaaa5SUuVIBAVAEyn4E+MAEBQGJcoWghVQTQ5UHCQn4aXLFVIibqRCqkAgH6UlypGyccrCccQQBUBJlU4ghVuNEQVKJMRMCRVSATjgIgnApMDlBLlBIRMpw0+OUpIFSiIVQBp8oAE44AQFekRMYBkIqFJMD8CfKcCYLFVE43QNTd3H63GA5QDwlAIigBEZC8YKCn4UF5TgIJuQQRGgvG4RROCCCYwJiJnBQP00TlCtF5UKRBMIEERAOOBRRERF44iIJhAo8IF5QAKJjAnygAUTAACbgIYRADAYCioAEMYAARECgoAdxuEHGMSQRERTDwBx+DinMBDDwBxhAoiN5gJhlhxuSKYTUyibg7jGaKJhQUwmTIJjI7hOUTjmJKYTCTOJxkMY4ynEVQCYTPuE8aBxxAgHMSBjGJIY3F9xxEHG4C8pwi8oIkziYoph4AExhF43AUq3FJqmECCcZgpjA6ADC0QThKHjdIQw9aATcmUTcBeMNTxTgUAiYCgYQKIiQUR4oDCAdwiHcIjKBwc8AgSPcNAcYZCGEQKBusDh4OKoEnDxpA4eAo8NBDCahM/CgOMMifH6wANwABuQHGGQvCLE+N1QQxuSLxwKAp+dFKcSE+MIi8YRpiPAQDAIonACccAIVUGEBQGF45ZC8fgIB+AgH6kmJupkE3ITEwgQFBQgKvEpCcCiFVBhAVAE+PzCApyEyq8xHlgBLj8ZpcpxokCoCTBUAR5UpBCrANMi/FIlWKoSKr1CXKcmkVcARIvwJcpxaKbkHmgVYLEuU5CRVSgQFOYmRcspEVgGiCoUIguAiAoVNMi4MSKsUEeVKZlTWAtMTcJITg6T5QqCEUACJrlcplUBymCnAlxhBMFiu0eUK5T5QpRCqgSkRcok+OJSZVOEkBwEmVfhtxODSILkYmCoAkCgzKPKCUgCxXKfKc6SKsQE+VK0mRYrSfKcklxxVpccATOYEyFUTpB3GaRKsA0wWTBIxukKCwS0yKgNMFOaR45mI8sCaPKcghFuGhy3CYmHuL1gHjMATdGgCbkFE3D4DCCZhEXAfgLxgAoiYCCIgXjCSURMNMwmAnHAfcIgQTcInKcIgmFonKcMnHBSAmECcbmAY3AmImAvGF0HH6QgnK5Djgwig8BBU4CibqCCfkFERAomFBBN1ZgJgKAwmAo8YCmNxJePwEMJgJygAUVAMymER8IiX3CYRDGEkomEoOE4FOPDKKvCDjikUTiwhhMqKJzKSm40hTCcQCJhcJjGhBMcEzHEghjCMBNyYcoLRDCdNMVOUkMpwiCoM0kcxykxPwiGOIJipzZDHFBBMYROU4lMTGEQT8BOMIEExgT5TgIJhGQxuYQTGEmJ+KKJi3IFUAkpuEfcPD4e4OHuDuMAcA8ADwuAEQa4QFgcbgDjdJwG5ACPAAH5hTcKC8IhxTgHcYA4DBR3CLC8YUF5QrAAwwJiYSSCfik+PzCgfqCcoUExPzgoGEpPjCJITgSQFCgXj8CfG4AKfgJxwAgKABeOUCAqDC8oCEj8LCCcUJ8fgTE3AQTgBAVACAoAJcpwJ8cAIVTqCcYZEgVBymCxHRAOKSYKgmjyoUkwUGWmCgAlynNJcfgSKqFJIFAcpgfgIVUC0wU4hEi4Ahy3DSIsLaAH5STlOBuc5QJxwYUqpEEKoWwgnLAmCoAkChNMyCYSiAoUogHAEwUASYKimgRwRpLlOEjyxRogqUCAqUaPKkuCAoWUQqoUJlU5iYHACcoEiPKloTE3KkuUK5TKsUSZVOGkCoAkBwAnHKIAVAaIn4EjKFKSKrwJkWKJHlAEnypQT5QASBUAQFXqEQVLImCgAXjiUmVQpROUKBU1ikpmMZNLjkGmKvJpcqEtPjcxgCncfpFHjlFERVAIiBBOIgHhGAiIyiIjKJuTL3GcEE4AUTdIUT9QXhMBQPwy8fhEE4CKJuGXhECmKcA44EBxuEAHMNMTgIpjAACYA4eMaAmqJKRzlJKfjAQxuAoGEAEeDgEQDjgBeE5AcbmyiYWdxjSiHHgKJwpFMIoKKnAnynMLyg0iiJpZRMNAcY8yQwmaKJ+TIcxhpnMLCibogeMLCmMZMgnERBOYCiYwwEwjA/CVxxGApwMgpjCAAcwF5QWiHEUwMJgIJjAmoIgQTGETlQJTOoAw4/FFE4gQTCIgqcIgmAoOMJJePwJioUReMIiHMBRTcIi8YBAI9RwcMgAYNAB4QAxeA3EFg8UjFOINB+DgNxBIExRAwl4QiBg4eEO4w5heMAAJgAOEaCiPMARGABEwFEQAoH6gOMaQnH4CCoAEBQQIJ+BPlOBLj8woH5CYqFoICoUkxPyEhU5CPKg0kCxWicYRJ8cQSBUEEBTmJlWKwCrFVEBQCSCcQSMIgQxwKT4wkk44AUFCgUFAAgKgCQK8CQnMCPKgCRVygnypQT5QAIRUoEBQBJCcBJicSkhEQS5QASKqDEuVASJViVKfKc0kCggkVYqpPj86RBTiUDKgJMFABLj8JIFQAhFDAjyhQT5UoJccASBXqlHlOGkCwS0iq8CRVi0JgfkEBTkIAsWkQFAGkVcGEKsWWkk4LcIHOA0gcFQ3BcrlEFgEmJ+NEQWASILEBIFyAkRwFQkmsQCgsVUkVbhIFWK0mJisAqqaoAPzZAUJIUD8CPKg4TIsUpMVOTS4/NpCoWRIFyMQMuQSQLANEjglJPjhLT5UHKQqBNETXK6IVUqRBOBZeNwRom7j9IvG4ZTDxHDxhlN3F9wiACJgIfhiiiblRQUM5SE/JF4/FEMJnJeMKCgcGiGODCibpCCcAKVXqCCYUE4w1ICPOiicQIYeSKJuAgmFsvH4AKcwEE4GZBMIFE3AQxgABMBJDjwyicw0TiYRDGMIgqASUwiVwiJQcfgLxhIAw8IBEQDjmAgn4CioLEzGMghjGAon4EzHMBDHKAGOYkhxEophFACKgi8oKSZlDDJyvJlBQwEEwoKYTAVThDhMYCiYQLxxAomMAcY00mcw1JRMMBeU5BeOLCCpzReUFNMwiggqcCfGNUpibhl5QoyifmJ8YWEHhAphAAKfiSgfiSiYoAA9oB3Azh4tAEFno1wpnz89nxfpsNanOD0X5mqvL0KikaRQAOkYxDkgfhFxjdLDjdIUR6kAHECiIyyibgIYRF3CcsgGERQUAkpjGBMTCBOEwFERAvGEC8bgJx+QkY/MTBUATBQQSFQATEwAUFAAgKgCPKdUJCpyRAOVsAODovGBIom6pKCnFJ8qmSAiIE5QAJynS0+VAZAUASQnFifH5CQqFpEMfopLlQQlyoNpprlco8sFJHlQBHlQISFThpCqRUmCxWJcoAJAqAJgoAJFXASALgCILANIqxQTBYrEiLlBHj80mVYqEuUBwnxwoS5Ys0mRcBE43FJEXJUJ8oAJCbgKB+BEFeBMqxSkOXKpS5QW0gV6aRBYtJETlJIChRolWK0nxwQXjgBU1SMTBQXKQnFUlxwYkC6bEDHKwhVeBEFAJTBTik+NwJpuCiR5UgJirw0eNwEKoUlIT8JIFuTSBUHRAOMiHGNSIB+LTIsAJgfiUuU4tIFCkEIsUC8oKpHlSppcpw0QWKBCrFlk4/NxgnDj9IoKdaTMfpRRExReOEsAOJRDCJJTCAuE3GhTgIF4TAQ/HEmYRllHjVJAWBBAOIJlPwk1gOMomFhOOIkTn5yTjimQTixMTGQmJwEQT9TDjdQQDCjjD0SXlAqS8pzCgpwiGPyaYnECG41BOPwAbjoKJzSiccWy8fmFMYUJmMYCCpxCZjCIvG4APxwKZUodxjyJmUAC8oLRDGEYcJ2EE3Bxynlccph8PCAm4wAJjAAn4CHE4EFQYpI5zEkE4uyGPyA44uSgoMohhMBFOOMvHEReOIEOIgQwiHApwF4wgXjcADwlFE5RFEwjJxigUR4C8cGiiPNFMUaA4wAXjFDuEKAA3UE4xbCFMnpCeXd8B/c8eT2q5JcX1HmH3HScL6/K+781+YD6393jfRZZkp8/wCw+WbLc+qqqSkAj3IOJRkN3CgANwcPcIDAI+4QFxh4AEeI7jCWQ/CQU3GAONwFMbkwA4JkEwuScoCAATSE44gkImYTjgBQOAFA4WE4wABVCgUFCgXj8CIqBUk44zSfKACfKcBONxJAVBogmFUQFQEmbjgkY/FEA4CKVXhpgqAEBTgS5QSEuOI0iq8BOUAaXKlEQFQGiC5BJgsBKIKgCQKhTS5UEI8oFpIFQBLliAlynSJcpyEOV6xDj8CIKiJDlQGmVYoJlV4EQWTApViglx+BPleBuCvOEuVBiILFGnyvJpAoCaYLFaRE/Amm4AlMqoFJcsQaQKC4RIsSkkVYgJ8oUROU4afHEESrcCKS5ATMJwSKtw0QWAaAOAE3BUalAFyjR5XkIlWKxLleBHlQTS5Xk0SOCCS5YBocrwIlXAEAXKJuKxaSXLlmkRUAaPLFEkC3AiCxQTKrxSQKgUQqoAjyxQS5UpRCq8klynJxYHHl9InH4SZjGAoKABeUAZeOIyCbhAB+JKJuNA4eADCMooiIwE3SFNwgAHECcbgTKsIkVRMMgnGkTjlpgJgAOMJmUR4CiIgURMBeMYE+Ewk+VAC8bh8Y3AmY3EhyhSe43AQxhAgnEpMygOEzHFMB44FETAUTGGmZTgKJhEUDnEkcwgQqpwTFQwygpwgBQREOYCQFQEFNyrafK8JMygoTOY7RBOYEhU4YGMaaKKnOSnN0HCYwFEwgAiYC8cwBxjGhRPwEE4iKJxJTUEQATGVpmEQATcIOOLCGHgKJjISFQrAE3ILx+clA4lpcqAIioJJOOUCAfiUhMFgcYrA4QAvGHQLxxYkRVLUSwGX+D/0Pz/etpVxz/WV9CRxHt8/ZHzqRoq/z7+msr5vo+FPsp8evO3q/Ifqp747fWHIuizFb533nRkTZCpk1EHEpszgMIAA8TwgcZTCYZeNwAbhDjcbMIfhYAKASAHFyXjHGQD9LKJygAmEonDwF43CADgInHAkvG52mJjOEgWI6JxyuUxNwAB+AoKEAomAAARAvGAOA5QKJxBEVeJT5ThpmNwE45Rl4wgQFAEQFAGHCABwiCRjcCYmERQPw0wPwEKsQRAUKSmKhVSfKA2lyhRE4/DRBYpCQHEpMqvAkVUCUyn4ZAOAJgoFSmChaClUKghVAYnxhQQD8CZT8xMTcCQnAE+U5CQLFEmCpW0wWAEyrFBMFSATj8CXGECFWTAnDwJ8pwIcpwNwXCoQ5cEIguVJDlQBPlQNG5XJahAVum0QUAEwVCkkCwSIcpzhHj82kCwAkVcoIgqLSXKFm0wV5tIqwIR5bgb8rwIgqCCFU4EiqgxIFgbSBUEkgVBNIFgKSBUok+U5tDlSEk5QS0QXKhIqvAjyoAjy3FRAqBy+kXj8xMTcgBEXJeMKogm4OAekADDcFE3Kg4TJFEwKg4TNcIimU3CACPAXjiCfKcIvG4fAcCA43VReOAyCYXACcJZDH5hBPyRR4RF4QvPhMKtM4mTSOfgKInAgKc0QTC4TOJ1SZjCUQRM4KImSDhUlkETNJnE5QAYQKbhJ4eOghjcwDHAfcfgATGlJicWJqccCCcEcIqAmYxjMon4A5QSyCZRwnxxQUwmADGMBROIEOJhhw8IBMIcInQU3HKKYwxRTCYEzGNQUTikXjGTLxhAoiIBwiAccQKJhYUDihIx+EUFAGTjhQUTAwpTiwgHAlPjA2TuGmUpwckEeqeET0EKqbRNvLGafLf6X55n7Oevub61kzkM59Dgp236J5kSuElc2ulSydA0/K2eJegGvP0/IjSPpR85+Tz/qh78/LB6i+h+U++rnzN6Y8D3HSzBz5XpOuRPmKGSMg4kGQxiigVCnABN0ggPUGMBszgMIFEeDh4wAIHAom4CgYQ4qgABVCkl43Ek5QAKChBhw80URBAAI0EA/UJ8oAFKYADhECAoBJeNwAVQADhEYAYBAbhKADAAccQIVQRJioCZCrAkiCosJx+lkBUUICoUCAsFCQqACXK8CQKgCQqACYKdIkBwBMqwUkuUKMnDzEyqAxPlCoIVUoEKqDlLj8CRVABIVABMFOGiCgiRA4OSlOKEyqhQTlSyJCfgJxuAhVAYmCgsSBTpEuU4aQLBQjx+STKqWggH4EwPyCFU5iXKAhMq5ASBTqEgWBSjypW0gWAEgVKJMFQKTBQATBXkJFW5DflitJAqA0eWBpEFeGkVbgQBXgSBUUJkWCRIFAtpFWASQKgUkCoDSBQBp8oAkwUBNMqoMRE4gkVYqEwVAEyrElp8oAkwVACEVBaJAqAJ8biYrlA5vSIJ+YmJ+AnH4CiJwJx+BMT8InHAZRMAg4wiDjAUBh4O4wgURMBQU4Cm4ZA4/TSZhMIvHFpMxwoT4/MIY4gQTmQmJxQiZUGiFV5pI5jAUDmBExxJIJzFJmNxReOJmnywIIYwgXjixIVeEnygtEMcUwAwgQ4iBTGEZDH4XAc8pM/GaKJxdl4xkimPyZQU4koiYkomMBTCoBRPyOA4gUTmYkcygJCcQTUMZIpjCwgqCJM5jKk+VEERVERDKCJNQRQBxEruMcCcY4E4xwT5TgLynAQVOAoiIF5QA4DGAnH4CcYwJifgT44gnxhBEThYUihWFKcATBQLCApzCGOakQwutUn4Kqfz9+h8Wu+2Fjcv1jdkjDel5kfvTfwL1cE94FSJ+b1cvph8nVr0+4+e+QPoT97EFbK9Cx13FeSa6LyJ4s+wdX8H0fm96g8nrfQ/DfoJ2r8zfu3v4Prgtm+jfJ/TuDx63B2ujNlZF1ETwKnSOgxycBzFFBxKeTjlMju44F43B3DwdwCLhABG4BJAeAO4eAAEQKBhAvDwFHigIcAd3BoAHAA8UQ7g4DCQQ7gEkxeAoRAQ4QEAHuDuHg4eNIQeEAHhld3cMAEQADcIo8Iw4eAgn4ExNwJ8fgIVUoJgoAEKqmBAERFERGmVQASEwtJlWBNIqgAmVQthAODAKYBFA4DT4/AiJgJLxuKS5QCUgUElAVAAoGEafHARAU5NEyhWiCYDRMTlAnCJmmCgAQD8CYKgCQKFBLlSgUTGBIFSjTBThJFWAESqcCQKGYjynMR4/AmCwSIcoURBNzCFVBNIqwAlygAkCoMSBYiEhWICQKgxPjCghVSgmRXgS5ThpFU4EuVICfH5pMqnIS5Uj0ICpU0yrgJHlQKSBUAR5TiUyLFKICgAkCoDTA4DJxuCJEwcfoF4/UE4wgTjiBBNwBwijimEZeMFIoiZhOPwBwmQQTCwON0gcJgDjdJwjwACgjTBbhk5QBAVTmicpzCmEwF4wyEE3B3GMCQKcBRMcEwUFhe46gAOJZDCIEE5yCCYSkjCcgoGFhRERgU4jTMJqkBMKCicQTMcyCiYUAJgEYeMMphOBDGAQCYQIYwiDjHGmcTkkMIiATCBTAcAMJg7jmAhjcAHEwEOIgU/HAvGMBQUMCRz8IBMcZBMZBTCKA4x5E+U7QAwigOMMUXjDaIJhSKJjUE43AHH5BeNzC8YQLxhGQDcInDwFAetFAwNlIfgKVQLAExmEA6PRm4+VVDxX6Tw4r1UWV4vrGtZMr3cEbr6ny66OCa8hgX8337u757v7u4O1fKF+3P7R638Ffor+icnoe16fnXfq+bVq/VMf4R97JcHf8T9J+hPzB5PO1T6E/K+2/ZfHfpEk/z7fQ/i7Pfrhur8x9A6Varc2zhRsrCWMmeaOJRA5kzoMcowH4pgESiAlHgEQ4XdwCESCSPcADxRYYB5ACAAId1hQEGcHEAxQ4ODgJMQApHABAwAEs4dzfGIYnjFFLjpiBgAxQ8AjP3cMQHhcPAjh40sgjyA4eAOOAABhAoHAA43AUpjAmCnAlygAmVXgQ5YBJlVKNMqvAjyhQKBgAhVSAQFSAlygVCYKCUkCpE0+OFJMFOEmCgKkwVBiYKlQmCnCS5bhI8qVUQFAQmVUaEeVKIhVijR5YrkgKchHlQoTBUEJkXASAqc0kYwxSRVytI8qAkyq8WgCxaghFwBIqvAlygpogrw0OVASQK80mRcE0OU4aQLcmgC5RIAvwJEVK2nxjKURUBNIqxaaXLACHKcJIq3DRKtypDlAJIVXikyLArTKqRpPj8QkmsWbTMIDLyhWkxPyaZVQBEDgwoHBUnx+JhxN3P6hRExCYiIEE/AnynCKBwAvKAUXlOJIJ+AhjcBBOAEE/AXj8BRMIEMIgHGEA43FCAmGmcRTLyhkI8rxJREzCCcXKfKCBeOKafGM0An6BMThQUTCwvGECGMYCGHgKbjAXjGIJxxBMxxGnyvAkKpk0jn5ymc4qiCfnBTH5IonFhDHFMomEAExwKInhk5TqCCpyReOIymMZpM6nCTMqIJqHESZjCSAn4CmEzCmFRCZjGAhjGAgmFBRUEEziZshjckUTighjGAhj8UQT85KJxTIJ+GQVAJIYwAAmAsOMIiCbmkzD1oOMQO4QACjwENwAXjBoEBQQIY6jERWr/XzyXxQzq5/SePEb0eS4/qkKahfOrmY3xD5J9nkSfm4S/mXc+06F9dn0WJ3nVbN6/qZVcdMl+isyX0pnpWF5x6cqfNzZh9Gvnxkfo/M/WnOcW9ZetwN5TOpc1sLaxMo3+Zfn/wC3Xmfw+rw5Zc1nvb+Z2r6mfGe1+54n6NI74g/VDy+3c1l2Pzv0Lk7VWBcyKmcrmSMmsYgzRxLyRhIKZu4AEUxA3AAH5PqRgILgTpGBQC8g3F5swE5ndyYhApWH5IWGAgAYSBUn4gDUFLiFQLxopyfEKCnwlDImBbkTSKCUAVMmdWYSHQBg4XCPJ8Hcnxiijh4yCCIAPcACIcBu7lRQOVyHCAABwApFezEgULYnypWJFU4CAcAT4xQKBwAgHKBeMAJ8YoF4xQADFAoG4ClOAiCcBk5QgABhAgHKBeMAABuAoH4CFUACFVEEgUAEwUACcoQCgoUEwU6oTE4y0uUKUnygCTBTgRBURJAuQaIqFck5QFaQqcCHLkEjyvCR5YCkeVAEirACIqACILFBMFeG35cpKZTiNHlQBMi5TRIqwEoioUlIFRNEAVElEFAQmVUG0uVCWiCxaSRHBIpAVeBIqpaRAVBUlyhRJAqAJgoJaPG4IXjdz+h3CaQnKABeEwEE4MADgwom5hBEXJTCZBRMVBQUFynynMLxhAhh4AA5gLxjAURMqIKgJkMJmCAjDJyvAQwiBePzRREwEMbkEOIgUxuGmJ+IIY/DICnCIJjAQT8wvKgIoqcgoicETn6gomMggidAAcwkxUAZTH4ghxEoOExJDCIFOJhFMcwyGMYRDGEohj8IonECHMYRBUECCcQKJjgQxjCIKnAQygCAwmAvHOMgnACiYRAYRJAx+AhjCAAoIEMbkFMYzaRj8IBNwyiYQIJ+Agm4sgnAkOMIEBTiilPxBSKcxMDjTSBUjaYmEEhUC0BjHoTOMB1cj74BV30l73HHaKaVx+hDKh2DfmYrxXyM9HwpnHOL+Yep3c48jr0r2l5J+hX1vro6YWu+7zanPeNmhx+4K35DcRfpjzps0Bj01jzV7o8o8y+e/qjz628zk+4a3xc+m32PjaLqTKkvt1BrBXi86Z8tvry48j1fhRePaHgFeVuSNStf0vh+svqN8Gk9uL9Ezb5gfSDxu+xOC94vsrqIGzHBkFJD8mCFRSElQCcM/E4RhIUDcmALFTEFDIHBXkRGcoZH2cmr94tuvs+F6g4CfPfTnKUgG5MaQmQEFBQMpPyItnMiDlYUOBwCIA45HgXM3MC5kDIWMgcFzInkWFM82cxFJfCbkJccjBEOkHg6QRDgEeEOMIF8AmILxghkKqFIvKdLTA4IICnDbCoFJPjlEnxwYmU3MICgS0uOVoA4GAA8BQUBCYKlQnygMTBUASMfgS5QoE4/MTEwgmVXk0hUAEwUBopVQQnygAQFQQkVYGJcoDE+VIBSKlJLx+GmVUBkKryEuUFCZVAAgKCNEq/JoCqAkyqgBCLA0kCwDRBcBogrySRVgKQ5YHKHLAmiCvJpFVK0kCoNJAsA0QWKmkVbk24qFJTBYCkQW5pDlipplVAEwVKWmCgAkVYAQBcg0wVKCZVQBMq5AS5UEICpxSPKcTAGP2HoEExhp8ryZOMJJSnMwAOI0+UACAoAinERpioURDH4ggKCWQTiCJj9Ul5QQT5UEgE/KiCbhgImAgn4khxEoBPwFEeAph4CmEQKJjAQTHQnxxQnyvMT5QzE+UFCYqCkmKphIic1JJQ3DIJ+AhxERRPwFE5kJmMcETnMCfH4QGMaRPlhEkKhmiGOYpMxxQUwnQmc/CIYwgQ5+YUxjOSCcwyGEykhjCAcczCCcQKJjgQwnQUFBYkZQwJnMIFExpRDGMIgqcMhj82TlBYnyhhJGOaRMTiNMT9QTlAAgKcInHEZAMNBAUACFVKBAUKBOMNCRlOoIZQ9iQusM9Dhkfg8Hr/28IW29PZe2jjweibziaRDfJD0vAkKOAflfrc8a3avThZeZlvqPevH0V8P/RjbzZDDvSFA6PNxix6Iw5day3HOVjuDdCz7ud8f+2fHph4LUmXfi+pTqXsWaYR7B+jHwpv30vifYGIY6j6MzR8c0GKncvX+QS5sx1r6BRfzHvePbv5ovP0PzmvjEznq8H0g+hP51LvfH96w8ke0PA9iKOkPn+gsCYyHEvSjCAyu4xQ4pgKKUSNcokFwoKRkK8mDt38k/rX8++71PjH6+8t+8+a/rlLxr+PK4gpvIBIDB4vMMHC4AOI0PE5hzJFBbkhYsKR0znKcfGIcQqCsmmo5dojBmY6skl6hWezy9XNETPl+umUxI04ABBxT4FDonkOKZpD8URiYAEYS8BjFGaEB6aL3cSBR4kgHAaYHARAOUE+OAJ8coJccKEgVAEhMDOAwQygcBAU3FFAQJDuMBCqlZ3dyAA5QDh4AKbgICgMLxuQQD8BQOQAAwgQqoAQqpQIVQalPj9LJxwGXj8NITgIhVQBIygDTBQoFKoII8oAJgqAk+UEaRVBm001y1CYKlEmBxVpcpzEAWICYKgSlynKkirFTSBYoIg4KCRFwNESrgoRBXmJEW6WgCvU0QWKNLlAQmVYqEyqgxLlSpoiYQRBUAR5TmJcflSPKcTAgoHP6ZTCYCcYw0gOLkOMIFEwJhx+YmJwYAiKkvHCpKCnMIJhAvKcgnHMxMxxBMFBAvCIFERAphMBBE4EMJgTMbgKJ+kIJxApzDNpGOLaZjmUJ8cwkxOYEhU4CifgKCnAQVQAhjiBBOIEKoYCccwEFUAIKhgSMYwi8oI0hV4zIYxhlMByiGESOE3Bwm4AMbgAxgAD8YAMY0CZhPYQwmAoqABTCYCmESeEwkgInAhjCBRMYCGEwACogQxhAgn4CmOAAYwgmJzCLxxAnKcNPlBAnGMCfH4CcoAE44AXjABeEGBxy2EA4AmY4gmoY+lA4Hxz6fn2r4V2j3B6W0PJPB17zZK+3uRfzLSvmx7Hy7iu8P5N7oLntNejCapAaD9R7SLufHZ6H9DvBX0N38R7jm7+cezzqjVhsfDrUbpcZB73LpcNcpLxn7a8YXz+MphtOeP6URkW45ZyuVgtLid+zLvof4sqfX5P3eyL5y0H3PA76tTOsfN/VtnCy3u+Vjfye+3rDz/T+NMndfPOvj+jhznSPZ8SR1/Bz78/3A3T87PrvKfqwNE0z5/2Y9Tg5uoeKCDGIUDinwGIHM7u5opuO0mCnMUtdYm8uv8zP3Q+IP3C0+h21OTJr8lHpyBiY0ZyQaqQXhlfPWMV2bwB283tuzeP3nVyeuD+CKx38P0fJ8ws/0w+v6/xVzvXP75M/z8RvVx/f6q/BMMn9r6L8kF9Y+jVa8IK9PL6epWHRsl7orCj67RfsSv8A2I+E/TPPf0E+P/2X87eCRWa5cocmUF+RGBfkBBczcyFhQOhcUBQsdE6FBKZVxuBHcYIC8PCIJhKRKoBKQKANLjABSHKSUDlAodwE43MKBuQQR4CgYALxigU3cBQMUAEBAR7gIJuAgn4CcYhROMUkxTiCYK8CZVQAgiYEhMYEhPwJ8oAJcsUExU5CRXBBk44CTBUGJCpyaYKgqTKtyEgV5tEFSkp8r00iCxWJArzSZVBlpApwkeUAaQLACRVuGgC4DRKrw0gUAZCqgCILchEFQQkCwAiCpEEIuUpHlStpFWISnxuKIVUBogqVwQFOi0QOGgQFSSJcpzIAqhsPRICoAUR4oAPxKfK8IgmMMnH4SYn4CibgLx+EmJjNFKqCRBU5iZhFoOOM0HGEClU4SZj9STOJpCGEwEE4AHGMBQV4ZeOIwMYCg4RMxA4lEFQEyicUJnMIkzHMNPlAAvHM5TE/NJnPwFE/AQVOAgnMBBOIE5ThFOJpC8cW0jKcSXjC5Kc/QyHE1IhjcwOUFBROZCShjAQwmkDlRAnKcAccwJmOaghjDIQ5jNEOIklE4pEE4ug44jIJztJmMZInKCkmY5gIJxAgqABDH4CccRkE3CLxwYXhCgAUBifH4ZAMURRODafHGmmJlG0zKGoIdT51ex5uhfJlf2X6PSLk0Tr0uqQ43OWHgKv+F/R+dGPTlPyz6CMknNh6fTbXha4e97kFYXLm/PlE3zc5th+h3gH6LdvnoYN6KxXo44ySkW2XWzXh6NXPv0bAWXWLP4x9reMonxZPxc943pI5Fs+S5zoqM+PdvWM6s7Hgzqf2Ne3auuRkmWCfQ+BK6lQj47a8TK9N3wceMfZZeT0PgvfPrH8j/Pz0SYxu4+94V2lkSa5PPa/ht33ef+gaW/Pp704un6FJSLPyOso1ul9XBrZPPGXdEe2DfOqk93n/AFNd/Imn7H2zlfg/nxt+iOP/ADgtHy/oSJ+fXXH0ZD9NPkVv/mfQfRLP/DYfSfFevad5vDZa1laDv0eKLrVya8vZWTTIeP8AQRTlw5vmauW5tOZRu5jsup6stHu30fxHksYz5aRUhGRRJ0n1ax6HzZZpSr22VX74/JfVNck2r8+3Jr9DffPmKMp+/Yuag54EOInSXFt0joWpEPDMjA7O0FDszPkSBo9REidirFPTtVZavApkw4xUFA5QIU5AKU3AQpwAhTAZlKoQZQEBAIcMo8AgAeGHAIAA8UUe4jimEEz9wcA8MojwgEQKAigAiKgEgJgAOUBMnG5oON0BQV5UjynOSApyE+OZtLlQTTE/FJFWAlPlBBIqwFJgoIJlV4EhUBNMi5GkhUBCXLAqRBbmIcuCG/Kg0kVwBSJVhSQK4KNAFwGhywSIcsDEeVKmmVYpaYKgCRFgBEiwEJAoBaZVQBIqpQICoDR5UiEirA0lyhVaZVSuEyq8UjynBX+UDn9InKc0nxuchxhVhxwEUT9UpiYWyFWARDCIi8bgLxygBxMCZjcBQU4CiIgUT8BQOYEzCIAInAgm5CYmB5gYTlF44lFE/IATcBeOKRTH5MonFMvKcJMTGAhhOBBOAACoAXjmBMTiBBOJBeMYEzHESYnGgonGWUTGBMTiJMTiBFBMwOOKA4TCKJ+EUwmEUxxAhjCIphMUBhEkBPwdwmApjGQQVBYQxhApjGAhhMBTGMBOUMhMx+aKJjEE45gKJhABEwFE3LQvHFyTjiIoH4CAfhJ8fgIVUlMCqFLKB+oIBhBPjGsKpyrfOjfJD2fHvfg6a9Q+j6BFnlQ16DtHGqJv/l5XvKHf89zDnP5N7ja3Q+j+p7ULbnNp9b1n0w/ebcsfE2muX58/HS0Znnv30Q8CfQ3t40ME9C+TevjfRUTN83XFytvmceiSSsFc6uG6+LPaniq+fyBOQ094/qJ5vqFBI1TGovWlnWvrPIkruK4Z+cfd8iTvzSrVNyk/jxXufy/tNWc62jr7dFnMPvOHRdQkVZPl15c+8/mTyvR+ft5886J7Pzd5dwj3dW9GqrVlbKvKO/X8KpvZ+D07nXQkrjnIHrMinIvm4uzyUPBXMsjFJRUtpOV7PG3l3Z/MPoTlpFvX0+mLUrXG+2E3J11CN7IyBu85O4ahk3RklSnEXpilLxRuTtlI9290yijsgx3O3fN1cqwk4TfmnoArZS2mSLCiU5v7JeJ7+g6dZ/BPzPqeT/mOlI7R9IPSnya+9UV64pNXv/V5teAIzt8uTDPapty7YPl2mduXtZf5z0/t4/qrIfHTM4Pu9H/nyqGmH6Ds/wDg+l1c/wBtcw+S1Zx3+o+T/O/65eJ7v01HzB6i+a93gMXCgKJQKXgAA4ocHFDijwigJQ4OAjgEC+AQGXhAODuF3dwF4REHDwAIgMB7iQ7hEAG4CibkygfhFE3TQAYEgEwgUDcMOHiSibhkE/DIBhGUDgIhhFUBVAkSFQrSYiLaYqGTTKqEpMq3AjypWJgryEgVKUTlAKTBQQRFQEJApzEgWAEQWKCZVizaXKlBHlOGhyoCRBfikCrckgC5FSRFwaRK4AbUynEocpyaPKcUgCxRpFVAEgVAEiq8CALcxDluZXSqlw9Ehh50AKcSnxykDx+KIcRAgHEExNwABjAUDiSkcwtl44pk44tE5TmigcwJmPwyAqBBQOKAEToKPHBPlAAhjGAnHEC8fgKY3AUxhApuOBDccCH4wEE4yFNxwLxwQAn5hDG4O4TMJxxSTMpwFMJhpmMNBDiKCiYWEMJzMnKCCZxEAExpAExmEEwsKPHAomMgpxECm4zXG40wAGMjhMZWQ4iSUxhEAmEAExgIYTgUTCAcYwF45iSCJgKY3FAJhJKJhEXjGAoHEZBMIyccaZANzCAoVgFUKBAUKBAUDQKVQxaJlDaMjqM+FXu+FcKdY9nv2m0otm3dD6bknhtJfI2Cw/X54zNc/wCYe4ay9cfa+khNNYXf0OmLsbuWrmMs9Ltwsanbadnz2+Gnohv0j9GPnT9HenkZeS/XWD9fNBXNox4PYExYa+fVqZKsevit3in3H4m14/ItiZ2DzvSb+Z3Htbzaof0gK69DoVjmfn/1vKT00uP6KY+XURTvnfP7u74f1Xfvr59d7nF+gxP48fWX72J/X6tVMO3YG0bZDOgfJT7SNuD1PhBtu/8AzVvyvWRqHZvf8mJmkxxuaZRjO1TWenVyNETLsO/jsDnPnTzuRay+qldMyWZjfbLd5TaXhb7HkMrvz3yrpOVqg+nK+qdsiIwSbYiV5SUe5YaJwEijLjrAiQJNsmzuHbJ5EmEq4btq6El46QhnapsLwk2fQme3oP6CfIteOH6MfLefsK7qk7nC4dRNXyN3v52wwVb73PLfxkw2XLBKvg4PQcumBcOuUK07DV2tFpVSzZFOKBkhHw4yAtPoDyPV9Y+otQ83/L/SUX6S/NT6ga8cKmolnyETMRBC8UBIJaOKIScJOASCAcHFEPF5huLyYd3B3BwuKPE8IcBgEozcHBw8JXcHGY93DMADNcYBlBxuKKJiEcI8IBERhxuTKJhlFBQSkgVK0BVOQmZQE0+OI0+UEEuUEEuVKgnH5tMTiWjyoTKQqchAVuKRBbkIlX4pDl+BuC/A35cBt+VKCRXJE0QWBiJVwG3FTgQFUJESrAJDlilolWAaJVygiCwA3BcoJArwN+WKUiKgIRBUpKXHKxMqpWJ8fmV0qoYeiUFBSRFQtBeUESZlCtlEDAAKgkTjmoRMpyZOV5InKdTIJhAhhMIgn6ZKCggmKnAXjiUjyguEhOKAMYQKJuoKBxQQxhQHHEEzGMCYnGgvHGQgnGQvHMBREQKYxgIYeADGECCoUCGOIFEwgHCYCGEwEMcQJyhgTMIgQxhMyGNwcImAhjGAhjGAoKHBITmAhhMBDGECmOIF45iUziYAMIgAnMghjGclE4gUTGAon4A45gLxzATjCgBMLRTG4YCYQLx+AOUAAA4gTjGBPjcBOPwJ8oFCYKlpkBThkKt1NIynWErsz+fD6Hw19rltAr3Wr5XHevFbVFaxqTnxyZZfPj8dGc/NPedrT8z9D9Sa2O7H0SxsAv6897IKyG2PEXRfPC0W/UHGNAhbBA6P1N9Fvmx6G35vSbnyyy3Xo2k0KzPOHq2uzTfmyG9WQ9R5182+9/FlYeV8uhvq1856NX9Xqm9jZGos8n9Dyhv7HzVvhb/mAyjvkMu7h+U9IDyNk9DvjS6FGet69YdaDC3zfSn2v+fj0f8ATfLfU40g9u7clk2mwJ5FujTLr+B8N9/PmB5fVlkp5m2T6T5aTLNPdsq0nAucuoraVhN+d23rjpzKu2S++TpsZZgGQYtWF3CL3nLz9ZS1UrzJ3cvpSCaa4yMnU5eNjxb4udoqPlBIpNSNSo152nNJRkpvznhpJOd1kox7no0dpNmnLVZBEGnbEOfVGP59cHId5acxr+OigkJQlZtXyptcUCMl8umbjoJ0lYY6Dc53NrwUOObLHr1kkUzw0bffPyb9APgfrah+a32989e/j+4H0O+fOp8e3rtBdvnyJonSpcUpUCXk0HApZDl4AEA4QBxdA4FADgU0MeLyDF4AHg4OMQGlOAUxABA3F4B7uA3FEBEhlIiXkCdMU1OKZAGAwCA8Bu42bDhMBDCYCAcwJcrwE5QZERWBCQq8mmC3DQFUQRBcBoisKaAL8DcV+Tb8uUEeXFDcFhVtxWBiIOOQ25wQpEjkg0SrlGgDgqECrlYkVco0OV4SALFBAq6ZSZV0hJgsUSQKcCJVSgQqwFpFVKMhTgCYH4EgWKCRVBBHj8FZE/Y9xROI0+MKC8oWhMTGcEIsI0zGEonLAJMVOEUR4QcbiiGNwF44E9xxBMx+Aon4CifgTBYoEEwgQVBJTE4lJmMYExMYRRNxBROJZOMYgom4A5QADjCBTCYCmEwBxxQXlOQXjmKJynAQxxqScY4JicQIYTgmJjATlBQTlOckMYVJRMIAbhZw8IDwijuEyANxwKJ+AhzGAhjCBT8IcbhFxhGTjcYYCYwAImIATcIBOIyCcRkMJiSicwyAr1MgnECiIpEE/UFE3DKB+bIJ+GmBwEQFOYkY/W0+VONIVh0G+aOvgB9F8859WytkPpkJI2LdfP23SfnHfKc+R7Cp8PlHFaZ+F+gaW3rn6/0ClmTtXTac2tJ9HCzO+YHLY3Cbm4bgIPKIz/QaHhGixz9PS95+inyn1Lv8n34z+dFG9DzvqW4+UlXy6fsAz+MdYmftFmPy5rfXzfQv56VL6/eL6lV187vf0AzRvUOnjaWwfB3Vx2bwUVD4Zdwr/PeghYXd09v2QtL2wez6kZB6PT8eSThL5ACgs/1qA5cob6wfKKnel4X6HKj4G+lnu8MJe6dWsOnS2EmDjyn8lP0FVPzPW+F2mWHEe7wtkq0o89rgq0igOOlRYXCE5tY6afxHZzTctR1N+ewMQfUyO0EKzUkUktc3wFmHTJZItxP1U8tURNkgHMbSSCqOmfIruhwFjat0nsOu5qIxSTYxs3WbWeXGkUaaJw2dQEqNsLGxZaQCx0aJA6qeuCoA4R0a1UxuUQ5s6dNXkk1XE12+Y5Q6ONEJdmlLKulH56WbdsE++Hz3u675Y9Qfm74+nIJtnO83X9FPT3y0+pr5PoHEWiqTxpJilQKPEJOUgCVKQEKcmKOEoAIF6kYUxTNyZkcKZqRwAJZyl5hhICSnFFMTp8g4k4DCmFJXijLOKRgESGAxi8pOJRij8AgcQFAnKpAIiIwNx0iiboZBUFCRlBTIRYRpCpyE+OZNLlBBLlhG3MqKaBnBFSPLgCHLCCHOAKbg6FU056CpmLkQZ89KWyK/ATAkgm5ZFdMlQlarUlCt3IFK3gNM7MnSCWruSFdZ6PQRUzrgKmNUEXCSZVQYkVcjEyqgCILAUjygEo8cEEA3IT4/FVoVAz7yGMMogKCCQqlYQT8wnHMCZjgBeU5ifKi0nx+lEEw0yccVCQnFiZjiBeVEEjGFBDGMCQqChMVQYmKnAmKvAkc4gkJ+Agqc5IJuGHHMQmcTISMcQTOJkEMJgKYTAQxuABPwFE4DAROCZlOEQTiBeOcCArwFEwgTleBMxjCJygkpGU4SZlOYQxuADHFBDGECmMIAJjAUwmAom4CmPwFOJgKImEHGOMphEAMJhBxzDKJuRwmFBDGFyURO6IJjAQxhAvGECcrwJCfgIJwoICnAUqpaCAoI0+VPbSVUGqTzWl/EX6XwK77jkHK+hBQuXdWDb0O68QdnHYPlcnCePzGdS0n8n9SznZCx+n7YXNWd3wr98q2hnK0cPQ15W0NOQD5rS9h5ZtJJZF5RefaBnmEaMsRbakmgoymlCvlAwehLCt1w0F/nO3LYMznPsF5fowcq+U+h4G+JR7u4aSsF82unz7R5VJ3wG3cd15Pc9sTy5fSfSMbwncOlx8utOdPNG0fTqHjzW2DtMbSgYK8V3nqAo+qULmE7YjV9cfs/rP58/pR9L896mts3VV03JnStGqYTw/7wjeX0Pz1XX7PfH7jLNJ4xpv1Py0XLytStpxVljK56u/JD4bPpWFkdJcJsJC2+jHkptkwm4Sam1mh0tcnfEZFGVOvWbhNV/dRzl2kzmbhkZHkIu0aZQBnpp6WaK6czHvWvSpVjEO6Uq6SnehVFhZ4XMQIKpm7TWDPsiUJlBc8KCcjlu4eQrGybQBvWcYZ7G8nQ6bs5CR8qhtvH6vs/6bRda+J9353fJb0v5q9enU9FT/Cu+33xI+tNc3rzYfFftisI1A7WsTAkBCoE6Q/EAFSk4DCnwHMmADxBA3FEB4oAoUOAQIIGMmYB4oApyYgryR0zAHNGEooExDSCICgwl4FODkHMQ6DmKrIJwVzOOc0hRUNNJiqUoBOGbKLSMbnuhplIeOcSQqjNpcsKaPLFETlTIRFycbPnRQb8tA0TBarWnpp6sCnGllQrFPs1xx5yeVHoNj5srG0+pM78vQvbj6aY+Pm9r24fy3DzXp+J8lRzr2FG4DQ0ep4PyxEJ+tahRT59NpvuZ3fl7PVE7gGm82FzGsOUpN8yfqSqpqhxVyqUgUK2QDkbKVToEiqpUi8oDE+Nw64ZQOf0EjKCCQnEReUAZQOYhI5hdpibiCicGiGMMiYqBQUTCCZjGBLlRpJcqEyUVBKSMYXJBOIiGMKaRzmGlynUJioJJBMABxzAQqvAmKggmcRAoqcCfHEReOYExOIiCfhFMYQDlBTTFUSUjiYsphFMDCYRBOZNIxjOSccVJeVBhRPwF45gTFQRJicwkxOIFPx5CCp1IhjCIpxFhT8aAOOIEE4gUwmYQ5uApwOgpjiBDGNQUxuk4RMACfgKJhABEQATcwomFhRPyoojzZeP1InH4SfH5iYnGmQTmdEWM+ob+RKT8rvqvnk/byjzL6ZCPJV+vjjN1J8zO7iunzubx3z8A8fPPkvoZ2wr3T3vomss8lFzqTrGU3461odBvccYOECbQFZna3EWOYhpRhABK8mec6FnOM6ioyPrZ2rhu82dB0Kh4GnrusK7+SXmLx9NvL9Vk/US+k84PNhboS1qLX5VdfkTuO935t3cuvY8/WLLWOd973E5l9Ka87qyIvdcjODPtOVPO9HzrGNAYyzCk1gbJGQRGfaZTeVzUDdYN706DvrHA1H6xfDM3veB95qVhnrT0swkqDIZ7TzGysnfzS+fv6IcH8v0vlNNUixe18uhKSqffjDRjtRKppTpMm3Hu2ycl6X1nnkIvamH8Y70hZF92kxzp7Gqk7PHI3U2tFq78jIku0y0YIP5Kk0eRpDV2ZopWZ49tMTMY9gI/Lazq0JjnVzteMp49GwrZBX3z7mv5xDDfdEsViMt9yjsVsfJrdouBlTWWPFafzdtClPo56l8j1PjF7o+pVT4OjLN4VtBz2j5T+3POfbHz28n+7fFddtdtdHu/LhIen/NR9eP60/ST59+2BNmjuP6PP7kxBXiGATFEnuEZCccWE4/ATlOQlynJpicCycYCQAwtIicREBQiA4eZxgMmBuOBRTASpo/ipI8WKqUGBePOSGDdhJKR8e5sK1VhNc9HXwDNOzz/XjPx7cvP9X0q8weyef1aspUmkTovZnOp2RRr2VzBq/IGb9aDVm5bmj4lCJl4hax1OuTc6qtGLZzWtzhqnU9Holdziu6XtEnhFgl6bfsEYpbzJ+a7OPXmUJeZzz+r7ozjbyhS/T/AJx37cphp9DXNg5ZoRcrEN4PbK2WvBlqx2ajUlg89DueDTcrfIfPHeWnoz0X4uvnLfpdl50fZ7elrh44zvXj+kKfy+3B8/uOa8/WrCtlLmtoUWAKu5Tnk2ClpxzNzCUIsZjVN3zEOX5Kt8oHP3lERLKImaLwi2U3GIADjTTMYUFBTky8flAFUC4KJxQmJjABTiwvGMCZj9IQT8wgK80TjGAhhEZRMYE+OLkgmFMhjmEmJgEBhERBPwBxhYmJjMKbhQHKcBDH5BTHACnMYEzDwAPCIBOYkoicCiYRlE/SFE/KgE3PMphEA44gUTcBTDzAMYQLxxAomFoonEkpuMWA8YQCYxJRE4F4/FFMoJBeOJYCfhBxxAphMAccyRDCZhRMYCcoIiifjQgqABeEwE4TAQeMwvGGwoKcCZlBbTUUearvlbCeZPq/n677Eeq831KNfYv+zlZaU2+Q3f5s/wCO+bfJHSzyX8b6lCfdWH0PTnrDGzWua0rHP3xLLNFNOeC0PK9KnM4Jt9AsBKQWc29+4uzvPUN1sVx5Zofuespee3HpptovOCfq2VqPGlK+lvzNfHTPXWh+1eT0GaruvfR+QXzq90SNWWH1/wCXPZ4MnUOH8x9dVawSff7xbcvYfQ7enizO2LeajnFc08du4cLv41zpzuc90HNMTTkjN6EUjkQ2o98pmDsTeQb1rDsJtrlpC1i4wWazb3Z41X6eL79LfCj7EfReNZNBfZ/HZcY0s3rFG+V/15aef6n54NX+iHykOHfkqmt9X8y6yPfcM5NdGaVOqXGzIY8x5urfTebbsTokTljbG9ujcTsM3tyeDPrWzjgZcdNci6lEY1pK2b20uYg4OHxq1VmeX5+iEdjJIpctaGi0jIeyKwVSamzWV+I0VC5qRLUo6rDiwyPfnRrRaN34fQ8wl+n3r/m6vjL6w+rsLyvLdlSkjmpUnMqeh5yLyRgjK2v83qObrma+jKdn6PkDwt7x82dXV4VuEITya01i2mOmPsfevFXoted7girhVevnZnOtSTM5UkaGenJjzyCs1GGllggzTi4q6NtdIo5dALJnxb1C9HLAGWqfVz2k2WVzfn3fvNFV15fYBPD1U6Z+hZ/l7VNb+u0h8W6LPN96U/z5QXRH6F6x+eZrT/QtWPhYkq+0mU/KNx1c30tr/wA6T3Puui+YSze6UGnOdsa1UL0wz3zuqaXVfF9/6C/S7FPZvxn2WNBprHkdIbXyRiadL3DlFRLclZjMLXa5YVPlptpWBF46v3laYrIb8t7etUF5qVqehVDPsrVA06LXXnlR2qNz3ym5WyTWeW1rc0HWCLabGa1Qz31KlSI5jU9N7FQ4mr3pbo6hMh2qBJ3PVFhtScw8kJuKmeuH9vlsxrynL+w7VmvHNy9ZTEY+Xq77UfXHhxP36ZZfOc/0ifE+JdQ9JvzHFZ7YV9uXNZ+2IaY19Se6lAS8kN4xrl3zhArhMkgKlppcp0xWQUHH0kxMLonGECiYHAcfpAAxqovGAYiPEgbjElNxwTExkJifqlMx+TKImAvH4ABQEF441BBPyognECcpwJipzRDCYRBNyOA/OCiYRlBQW0xUFSmY4NEMfmEExmFEwwdxuABEQKBzuEjGFoqg8jh40gcJqAMIzoHH4kOOJJeOIFNxwKJuAvH4CicQKJjAQwiBRE4iGMLZTCIAYwoKIiR3GOWmY/MKcRccYRVlE4oIfjWcI9K4Tc2IGMBeMYCiYGAJgYHGMBAPwFERGQwmLKYxtApxS2h38Xs0uv13h1T0gV/wfThmzXR+vijJSE+N3R5kngmnXn5D1fN85610Ly/Z8QTH0j0j0vV+XNw+p87pz/OjTPYBN+fzDYtznLy89E9b2lx4Ou/tuV15/GFt9R9efn60a2hpljTHay3ni8NvTe88ist1QYzmGXNPKW2+QvZ5Ye77ztfhfQIP18897xXeOTt8jeN8SVz5z7+E6juH8y9k7p/KdXrXl0Lv2PXl5Rk8nnk1jXq8aC/169Eef1PWjPWfLavrBlpHmnLvfDvM8iN/d9qK+cJPpvJh81G/06jY18Vz3q2JZgDP0vLI8n1f3hLs+c0z7/i8uj59Qnu6iTLz2Z82nntfPe769ZpTr5ys6TatE0qGkR0dfxUp33S8I+f0+QorGbJ73zcxAa1DxvkpwT+e9FZ7HTm6y6avj3CqmNrP25V5HSIfaauys0Zy9DGyNYzbHQqZU1sldk65dstGkBatBw6c5Q2yyzv56jvXNn3j55yn0avHPXyYgPt7d2/ghM/oAm6z/O9ePuzBZ6fHqyfUSvxr6LnahrfRxRnT7bo5Cv06Pty6Q8oOOk7fXsNkaxsrLT6Pld3l8Bum+Eg7QyTSy+LvYGHb9fzlzT0j5P8Al/ptEtuNWCMvTf1e+Cn0u935r7lUv4aUb6TxPvUb4BJdnN984r4VE5cvtBHfG0+kfVmG+ZI69H0Lr3hh++X1LC+flOuNjq1Rh88V41q469IXlO5e0VFR5tWvS7S0wbvO5OhtJNmk0+dx0StLClDqtPY86c6uCRitC8hBGUvCi81aUStFxosVs3i341heImogjE0b6jlf0X8Xu9O+6PkZ9h/n/YrJXavLyMnLk+Y052YlpzssuKcPBRH5Dt8XPXiub+laCduaUTZ4DVUzScQkeni1OLrWL7HofRPnBH6T9Lg+bEtOX0mN4D1/nvR8hZYT36XvOM2yjry3qP8AOSNm3p5Apj16uwz3s+nTWefsp10VHOkRbDefLjzm09/af8s1PP6Ps3fvh/e8ef7STXyG0CuH6fH8UehYexOM0koi+KQYJybA4Z6KuE3xmnyo3LcrkiloCyNIwLcNuVwVJuC5dEkVchKPK8FX5QvJ6JDH5heOIE5ThJic1NLlBqEjHGEmY/NlBXhkEwklE4AQwmoIImkKB+AOODEznBIph6wDD0sOMLA4RAB4SCmEwiCYWFEwsIYwI4RFhRMAcIipATcBeOJBBOLZDG4AE/AUwiACIgUTcQBhMHAYxRDG6XwjzXcfmimE0Iom4QDxgATcgBMNUU3GJDjcwDDzB4wzZRPzgphFncYUFOJkEOJmFMIs4eMAcYQAREONwgBwOHdxgDjCAcIgAm4ovKCNMVBbTE400zmUbTFSn9XO5/P2p6q+o4IjRFH/ADe52Nx+99OKOdwfx/28dawTmk/JfVMNReaT0dsdoUtfu3CKssjJ9HlISKEjvznd8+2z503YdPBY181rmuW6OfKtZeftZ58/PcHH02KMsHzTc+7Y74+U6Ob7ZLfDaEOj7yVn4fvebo+0xviXoPRyIfW6YvXk++2ejivteS/jJafWhPltVsVz4IC53fTPifsMmsO5aD17YPdfSF+69fN909FSvXw4xa9GU1xoiujPryyRrtzy8sas2inqK3ZV3EjtVqFZvU49tWMoiwb3L1Fo3pSBWzkaDZ80aZNXUTtis3rMGsrTX6DScttKoV7sPj+75V9deevEnZ5X3LqXzH+oXq+Y3u0FVsey6xU+losN+RP3NifM9n4Rw/tLxdHBnd29H/Q3FfHZz9p3nR0fGqe+waeU/KCw/TVtGnz/ALD7gPNeVdB3SSdZpZ7w8qa1MPUtk4GLjOjGeQq7fXK1tqye4l2iDq1HhKttckHcLUd8NQUxNJxuiXmj0Ly9C8ErL8++07T5Rr8+drdQzOpaRe2juwlUbVqlRKj0vlzzSIWd3Ck0bt59EzC6udpYEy9tvCNMuNMnsxH5uesvO3xf0MLb7HapqMvLB99F5VylavKetwS0hWX5lOnYNKdhViGdTMINI9E40Ejo7iN7TGaaQMhntMBHKulW7lJJkRieak1qo7VWUkZIaSDdV1QzaTEagkdIRGcupWv8tbC3ayWrryMo4MoEr9mhzEu4s1cO2UirZwdqSSpq8tXsm4+zPxL+5Hgen86PvH8Hvs343obevOuOThr3T4zNfJYW4oNRWGqJLqLS+jHdAw7H9s/WeKZthPdn7AyzxnnvVp6AyjIKvvvrkNlDWavFNCYneFezz2VVAuR89YBd7WFrIVl2rye9BpztUw6pU9Ji8q1EMwPnrpbKgyEVZG8fKRoIS0XMpJcvrzlkJWzEUcNUdEY7fZedfJKazkcvnn602n5p2fHn+rVl+bG+8562XzfQMcnQmEkgH4aSbkg0SqlvNEFS1CXKkBMqwNIcrw6ryncfaQTCIvKGeiPKcJMVOJIKnNJmPyC8crAE4MATCggKcwoHFheMLC8YZCibmFEeAhhFgccUJicaEzm4ggmMkmY/MDjGBMTAwBU5BeEQATcIOMLgvH5MpjC0URMUU3C5DjCACIs7h6TjcLgDgZMBHnIHAyfCBhgIiUBhEgBMIBwmKKJhUgBzNEMIgAm4AERGAmECiJhFNxg43cAiIgA8YOEDAB+4OETABwEBEBoEeEBEBo43CjjAM13Ca64eFAH5RshxOUU62M9/Ja/z6u/Zvv4MbGCq9Z9hqnofbNt5fpvzF7/CvGqeRZP4b6H2Tqd20n0fXwiQyvzKvK95NPGlmz5/SlRzmwVJPb3jP0z1v3F400jC/d8n5nk9MWn5D2PLM97FsWXX47mvYjvTbx79d/G9D9Hh+mvymqcJ6viwOrwukeH9A9s3SW9PMzqVKrKC+vUlKynD9l5y9zxpe8Fr9q0fIGPb8udf0ecvfzX07DQpLVe/nq9/kTev51jtGeE38zXVvO9RrH2NJY7q+PpSPYZ4dvl+qi3xwjpz+0a3wsiMr+9zv88XvvLf6cRUplu7zTPPn9XOWfoDT/Mtj59tmpsNI5aWb6u/I/6bd+V1+L/08+au+HlRH0dpHznp+NpH3G+y6/E8r7JSi9F9X+A657XmbN8cPf8A4b8vsuGwUez6X9edw+BP01+l+e9DyV0qq6ZKCq9+0mqYJ6ZTw7fhap9Xfkr5y+kNo+L/AK5+j+b9rH8Exbv6QTHzDjuSvqy6+RVVzPtOv8M6zNfe4PgOnn1fdyG+HZc39j6X8pTY6fROl+JFYr13D+X1MujfqXm5sastLfG5dYRGxBydDPQ4fdZ6MT+5/wAjvtN08sbWtAY+/wCDAzVehejludQvS1vDrZdcm2ztacH3RkxmXee1Hoes5Va9saXZ57FdTW8ddL6XT6Vrny5nroFjY2n5j2I0kkHRlK2KGc+jw2mfpjnpm6NU19pYTSLslI6LZJ69awLL4jRZK5tPVWQELWWSndsmsxM5Kaorgm3Mo49W8YKSCuuoTRZmOOtFxpZXVWStWMldO06RsMfURSUgSNOdMYtqwKwJrmRZKyWjrTWdjsUij0QqsTODbRtrP0HyrEflvdrX16+A/wBj+LL2jR8Dwj6X5/1zQvGNX6Ob2zDeMU5r1xX/ADBGOvQ9QxRSOu+VyvMOf0puHYpc3pSESfub0I9CwyGPRQR0okaUN3bX6VLG/OszN1dPLnpmymlPh5a226czPNYernGd+TV/Ydhxrw/K+3HV5eHpz1e7I8rOPUEeqwJ36Ovmb8JNfo9N4P5tzPtirp4/sVg9BZ4YRI+nJrkz8fW71E5WWGH3s5nktquYvOPduOeSILFBHlebSKsWoTKqWoSIuW0iCxU0QWLUo8pxVWBQOHsKImoJxhEUFOGXjHJTE3KS8p1WmJxEQFRJTE4gQDmoT4xmF4wplA/JABxqScpyRBOKROUGhPjiUUFBYkYwuSGMMhDGFhBMLCCbgATCBQOIF4/AUTGAoHERRMLRRNykonGhIxjAXjigANzONwgAiKCmEWFMYSSm4ykoiZHDwjA3CIREwyibhlMYxRBMIiHNwg4x6RBMIiifgKYRAoiYCmEWFPwugNwk8PCHDxkd3GZ3DwD3CAiU5QiHFHMU7ONxkzGE96g7N5d9DhivjiT3R7kkenij0ls0e+gtZa/OSueIOrxggFj/AAv00eafV519EJf5nPvb5vpRiGL+i72TlXMjoo5a0SPTz59D7FBD885z7FT4TB9Y0a0dmVCsNhY9/JGs3TFJlDWyOw0zqJ2iY870YqeQj/a8+2+RKF6JjzaZ9TlD83tJpMfOfr+U51xDzvvndfkVA3bzJr7u14l8r7mi+x/n97p6MvbVNkK59Fz/AC3T9cvPne7yjJ+vJLLXyJKerE9L9HerfmSb6DxfUfz11BtnVCvLu6+d3wEhPO9Sq2PoOo3es+ScL6PO9QKZhunN1zVhbveqDsnkvc5vQtyR59vIdd9FtfN3zu/aJN9+dLkNLT6+fKj3RznWaYr68Y8nV89HvuiC8jq82F9OUzo1y701mfqnUzH255S8re34f1dzfzj6w9fzbJI5F4tw2ssq9c+X34f4k+oUD5Xq/H4ntPyX4HnwD1XQjWluNBd9HoZ040l2zNHGpyIY4rtDi6xd3tL0eJOtuXq8Tc7YtTxVba3TMQdbUqzHi7IWii+o879lbHmz6W+XfX/f43mi/q577Py+jBW7BpGaXiboOuNtDNr3vhSaNsMC9Ikc9s+0jX7QjUtJbMZbohlC2Sn11YL4ddSPzvqObBAhJLvGDzeJ18k+6oaPEWlYv52ozWhanuez+uVhdV/q0nEYw9ZSUQ+IKKcyMFhrIrx8vSXd1Z9oOiS8W7FSPdGTZ2yNFyYMnOqfyNZM1KwcmRFaStCcXCSSMaRZTwBb2vcfTlW3zOdSJrEVeo3Oo9xHRaLWlWVgVMiXLT7OfDz7sfn1+L+shPtv8PvsVhy+l/PHtPzP73o+dKlr9Jz1obe0NOfesIW53yduXtNgPhWNl3hxnpgSm3vE/OKfp+YWPlN764l5PIct7FncNvDanvmRyPB939bIYV59nd80jTk893T0O5nDzC829aLyGK9FO88/KQerpCX4xk/as7WfgaN+hhRfPS5e43RHlG2eiSzhk1rtyrwhW1k5xXFZwazSOYayATiCfH4CcfgTFXotID8qTKqUkhTgSmRQuiT44NJgoRMpVApJcpwqrxh5fQJxwUkE3M4TgBREQTObgKJuAOMIkzH4ReMYopVOJIc3NFA/CIY3AUREgvK8WQ3dQA8LAAwgHG4AA4iKJuIDhMBBPzCGHg7jGQQxuAom4AE3AUTgwB45JDGFIoiZogmF0XjHbTE/KCGMLCCpwE45hEMYRkE4iAR5gGERgI8HGA6AOBmAbjIATiqJywiSMPOO43M7jGVEMsabbrLus9mrl+r53vRASpObojF3gZjRGeW6+WtHsBt8K8FlPNVM1mbdPHCFnU9MocZZwyDGeCbhBmm22TFV07ojpB38hfY4dS+cVj9iepszcmqu9uoec0ek4+R9b8+aePHRsqT4z6cLGrZq3VtBrn1VC3I9k2yjZex2Tv46PM3dfqwpq9wR1568tblWqg8sb+YpQ3kuudbsLwKiMK4EkZRuSlyrI+mTX5svfpj51Zx7Sdva9FCrNMp9HgjtPc+HezC1/MOZz3zyV9o+OPoJ8j9FTPJXv/yV0Vnc9qL3kdXbXfQN+WE0uyWT1caie9PN885Z6YrBi+e+qZDl6fA+/b3MZ1ASlna+z5UDIPJKystrWaHn9e1pty9VAuC0xtztF3xunki5Mk87pa0msnXiErmO9mRrymWtoQi2uma6zQkOR6N4lGO5njqevS0Vlsz9eeYvXmd1Lxn9APGF9Hy89f8AlrK/P8z7EwHyw9oelzaDpFir0+noVVza1N0jENXwny/Ri7UM9z6s3Nie7lWezxm4l6/kWQ7q0WyjNHWxSDjFVt/laPNqnqOwEeQH3suDI8sLST7XCvN7S0oV9yeNfeO/PVN2zDV+rzM4hhlPR8TIoTa67ZGTmM2TfnteXW2xl0xxVq90YXXObq00qrS7ai2X2rOk9CE8VervmJy9i1hiO+d9abYIy+uTCxrLdOJJdqvuWZGuP9856w0wuudiSSd2isXpE0n7dsTLvK8I7+1qCu2T9qLqNmUXdDKa09ewrcm5iGyq0I012nMsnjypiWp1lMNMzVftOWC/RqvNVMyc4kknvi+YEncuirmszpqlGssCtHUpVEE7GxFkwXnevfM29afCf6XfOH476un/AFO+bv0Pwr664J6kjPO9nxPWPdLPLp8Q2b2RYzl8fv8A1y/z5/Jinr7jPx+t65K15QV9SHDzJZd0RrDKJDTi6YZ29vCdZMF1xrIhzmKTUEXBlUhqVlW/JGOkMC5EypmApQUKANB3EAQHgADcIvH4RBMIFHjkk4RAOHiSibhlHuy14DdDTKqW5TIqDSQKAxIFStJAoFNLlCpE4/J1Q5x5exLlBBEynAmKnAQT8BBOLExOLExPwF44gQFOYXjcwvHKpAxgaAREA4wJAJukIJxtpgpzReVVVNTOTRo15307NudjOjUHfOWpnXCaC4NWLYywx0omWGaQ5wZy1Mvzhvywa8RBOOmYApyCCYzkgmECiJ0E4wk8B+oKJhAgmMAcYysOWGN0DKDUJcsjNEPwDVEwtFUKoqUVIrzeiY/Kc/dynKc/YAKmE1B8pvyMnLlHn7BVSU5es/JuGklVu0hJNwTl6m4iPHsVVPlL4iKnTimuQ6FzID15LmQGoXBAm2DsGgb4vBYj08jp/H/GH2eHWvJ01u/d6j5ZOg+74ryxTvVzuvjIwzNeavsNZ9F/L/WefIPXK/eETapSy7ttaTWLv50JjpXr4gmIhnvzW5WoG0zuZKuS8ry5pblzZHtSay9AaVVxWdyNnKdF9jIKbUnhJx+nnkVttPgb+6PC3rmd7bly7Lo56pcpf5I9nNcvJTOv+R6zarKpfF56J9Hfnr9KPU9Fl5s9ieTvUzslljJWYkrRVZ/bC3qxaXbzW11XV05h305jtESbh8OEdXCcapFT2qzVHmVL1lZk/ETL6EyAvnBO/Q4EfPeU96cq8Ore2ys8cSXrboy8svPTBSsOteiFp0Vvf0qzq9G2DNtI83PU3dwydBIBWmk6XPWrMrbHZbRHqHzh6fxoPHHtjzMuj5J4v7M84fMexmXPQ4vnr77y+crn2dfq/wCYswvfR0yGwxvpddmO2jTJjqihWi1S/ThB2ORkdcHTxBxfOJXTx5w5p8NM4two0lOnEVJg/omjUCK8YycfIzqPCnRMe3PEXuS8WulUPRdePzzXJx73eTJN82kdcrfkd/O6xax2TG9Y01tW3mzz+YtFLKmHOd2vbOup2zyLevnShMpX5X2itnTmAVl1t5WnIwnTlOT1JeXVyZDZ+7kqLqbZS4R7KIprKR5bi+ts4dWrOZk2CWZybsuDJMJuYBy8JlSS71vrKxY5WSQr025VVJ3ZW6UGexDqq3MODOiihDNT0RX3WO0m+KrWaaErJ26SS7Sk1n72dgmOJGvRE1cY2HnGF+rfyj+4Pg+l8UMohbT8n9M591ePPY+EfZDTvNe9rhl0I3pwdJpc0JBACpKlkSKuVJHlgBEFylIAtw23OQE2FwM235fkICtySQqCCPKcBAUBBAVBiYK9IiVfgRFTgRBcBJ8cyaIqcxPlgUpGOYSYK8JLlQQTlONCcc8U35UiRAOXRJ8cCEgUARCqlBMFABIFOnRPlORVhU7DuSFThE4/CKVTqEzGMBONwF4/AQT8BBPwJmPwE5TgS5QAIcxgJwmAgnElMwiUXjmGkZQSQct18+hYQPy+uUFFufsbA9Dl9FoLgNOdLlR0xTBbteZAyptMkechFIAv1QmRUrlHjB2eOXjBfOQTDpkmJhJDj8MOMJJeMIBxjMKJ+QUwmNAHhViPdNiICQZNUCkhOYDcpyZDD1I6yJo1crsTc/c9UYjn0PlY48ayJo42PU85AefocqNjyKkA8aLgUxoU3cpKomltzPixwdnDImjC6Yy/Q4aZShYwNueTJHhpi7K2HXBwLczToW7938WK19dPlZ6vo3WzVPPPYVo3N7md8s98Y1WfJw16g3/N/mvY9J+lcK9Serv54rOsRe3PXrXM2zeao7uznr5qyta3WmEJaU3GuL+HeM9Od1KRkhUArwa4u2E3E0lxMQzZvCuZpsuct5x7lhV1V0gYaPi7QekKTWw+ifD8UHlDHPVsF8z7HlWh+tcR8ntzNRxZjzbJ9X/mN9d/e6Iryl7h8c+pwyM4SZzhxOM5bpy5wKmvM8rlohJr3u3ct2KHZJOJU1bc1M6eBWZLuKvT0an2SV0j0CpgdpWmpL0aIzepq4tE1e9RWLP5nS42jJTrfjUJrGmhvsm9OrOnZds+ZdXP43C/orWnSVqPSpPXptE01lp8ItM/9jeePT+WiGA+msWu/m7hHrPCvC9jz/EaSt5e1aucxcepNbGWV7OXZPRGN+q+3HNWm85frjVz5il837eq9tT3pwwZ9uARphAb8KfmeU9D9zdOFSmuoYdGZ7VUtU9jxq1Q9Hpn0vznhuZ6az2hm9iTaT90+MPbbyRutWtuvN5yrdYV9Hx7dHSEYTSLiNJ0LkzqVx3jPabqyEbQbKtn1mTrEmpaqvyp3TK/K9REFEvK6UZJuoS+t9WYdMaEhAyXbhILxs1OjKJuiu2UW7TbUkrNGsXN3RojvTO7RccJo7WQmKUU0nUbiITsTbO05CtMUXCXo7ZXemlZfa5pybJrFKNrG5pVRZ9DxpLFE45M1dirV2ks7rWeuyMszs4P2j+ZvGrR92SesK/SRm3MpXquzSoOjXLPWa+2XzH9d/M+58eLHBWj5j0rR6Q8/W+Z+2W/4Rv+/IyFEY53Kjc6hUAGDu7gAD8gnHMhHluQiVwCEir8CPKiNIFum0AX4EQWESHK8kjywJI8typDlgbS5UZSILA0jyxXKYqklk5QGicoMiQnFiQqAgnH5MnHAtMTcMpTgJMqnCSBQCEwPw0wVKmQFQWqZVCgTjdRWeP3P2kExhp8cwkjCYCApwE5Tmk+UBIom6pLx+GHcZheEWiccwJCcVBeMMtMyhaCicEcPC2AgZoBEUAukC0cqMzY9D0WPZdD9JuW83QtRvFcEuvFYUjAYyQ1JxT4SgBzkSmFwQR6pDj8ACcHJROIg4eaEDCBTCKopjKzarQeVcJRqDGILBEBDjBwzGTUEIcZPh45oURGdCCp2PaBk0/P9t2pFrY9D8RedPnNjuVXLMX5yo0kuXXliVXiXTwtyOz1DAZFFyz5yN5IGWeR0xfTJc9YcX6e/IzFYNM0hOVoDlFh3CCo5z5zfQiXvq/P9649NfM/0vRv/wAx9UleTHI4zRqD4/bQaNe6q8PWPr3z56++lPL8Tc6R18E/PVmS3i3GrJd+W4JVr0S5w9l7fsAvBzD6ITdx8z7F9GgF8+1PfaLXiZ/7IRMfKr/00NrzQ49GHivPD3eCznkV0tIWQkmZBw9Zt0tE1gJCIa8c0i9Uny+5rXrUz5fRxnIvUjDk2w77EfPD6k+hxVXwr9DPBXpeY2eaM6nXOJDSHF4Zu51Jzpll7HSoea9zDLMXGH+bPUPzlq98ivN0H43reqqJhMpg9iaZ7XK00qdyV4otH0D+Z30Z1iw0rWs68P2Wa6ncXUWy1nVqwy5MS5amUTGQvtLxV7Z+j8CqZzpeffS+B5oYIwe83dSspJWxpUl4u/xcLElWn1B489gY1NZTtGZ6P58Y1tub+d249B6FCeZ3JWlGd3HUsV7vz7p6t8v+r+zkkpBGSVOqk+H8Y/UHTZBLpyXRTJqSsZIxHXxGKRPj7FUxRsabDjm2/W/M16nXmrfc/H+GZVlMwkSqrsfe2/Fnt4lGzQc3rzeToyRL6Hk5xY7Jn7dpj6XK7ZytUsTodfKaiaxdK3JtXrn+Ybl8sI1rkjYGnzHtMUVgJfSMQptE+8qc9rnIJOCdGIkeTs7Uh5cU3LZ+1P2Yu5qqKN25Cqq1FlCrPEOUZdxaqji1u3Gfjdm09DFZcl4x09Ew+fRcoivSk5SCZHHRFbZW8eXSmPr63uoJ2q30wWaOnl6KS9MayXqMqbxXKyNdVmlYeWMUR07RuY9Y0VFzz6ryU6/Trz99GPmD8Z9f4uuNPuvhO5zsPZM5+x3rD56/RXo5avynRzCqRSZETHSDhGTuEwiibkAJhQnynAnyvAiJ+kICpQJxuApT8hMFDAjynAkCvSJ8oBSYKgUTlOBHlRJQ5cEkOW5UkC4MSBUpJQUK0Th4C8oBRAOE0QDiCPKACZVQBPjgggHIgAMUCgcoicPVNc7hw9QBEJY9w2cBhEUR4C8YRFEwILygMKCgCADCSXhEQccAAD8BeOIEE4CKCnAQVBJRMfqSZj8BBPwF43AHG5SHKC2QDiCZjC4IYRYAgcZQOIg4RAAOIEE/AUFeQQTgwBEQKYeF3GBXw9y07h5aD3DOvcJo3SBx3H6rBN8lz9rQ5W/L6bgqfcnedVl3N3yTliveL00ekokAjRy3eMk0fO9BmebbefvMSsBIe140kYDd3As4YO98Fz8bs4x5MvV56goj0ca6JCXmAFJ2eWYUy1i6dRnYdskg0G5dFbdcLEKFQoZIVSx0zPRVw0MyZy++Lx0eQvOf1WNj6HwA8h/Wnw/7fF86K97ryjyK9T+1POvsb6Pn8e1TS4H0uOIkpc2+DBKwl254T1V5q9Hkabw5nXPpauAxNP08fx/ngvfrfwNXU/oYj4SgrX0JU+dHr/DTUGjaQ8T1WaUwbh6q+eeRmoNGxr+f10RtqMrlpkshcYb9B+L8K1DWYPj6cxa6Cyy0zqA1qDw3qv1i+Z/1I7OaA8Se7vH3o+Yo0sqA2i043uWZ62gZ2uGhCzp9Eo2bh4rFfn99Bfn95np0RlJLfmn2Z15lqno+Na7m1bJJ8lXKw+h/gz6GfRePbM50akZdcYK5ee299o9v256QVdLHYpuByn7e8Se4fovCq2Ua5nH0ng+bZNRG7ULLxpD8UXYm7WUaCjfSHnn0xjrLZ3p2fbZ+AvOXqnF+Tqxs07F+d3TFkg7LrEg6K73w3L1Z5b9W788k8K4nWoKlU/Jv01FN0XLVqm9BpxD2SI7eNgD4ODutdPXLjrW98x7aPt/kYGs2yvfd/F+HLbUZ5p63Azpz7c8Ve25hKYjJrTn+e9pdVX0fNubbNLdtzTeX6QhO+YW5SgUtCjIOQ2ypb2WyaujyRhqj35r1wZyzDDQXjVMiek88eXN7LByXTkodeT0iOfHkrbMrtDWXD2De1EmIG3aTuMLkr+fPDbxOpAvWVVc2mSy2qSlgHUrziaXlV+RUZ1pMOIEdMJaEZtsOixpQCylIk65NIN0ZxJW170s3T3i7jRQysg0zLFFV+tzvoxM8t8oqcopsoA9sJmRcgnqvN2ffr49fbD5f/E/ZfHq81Wf8zHR7VVbnjHtT66/Fv7H6c0KV0mc5gVPDRMtxmmoKk2jzjkkDKC80+WFJAroBthccJAFyiTBUGJAtxKPKcCPKgCYLEBPj8BAPwEKqCaYqAgnGGaIYyq0IdwXk9puk7SvmalWL1eWmCgOEwVKBBOEtPlAGkJgGUqgAnyhQIVQATBQoJgoAJcoUzT4/BV+MPP7AcIgHccAHhEHDwCBhAAMJJeNwuA4AHG4CibqCGNwF5TiSCYREEwM4Dc0HGAO4wCDj8BR4SA43BxT8BRPwBxhAgn4CgczSYnFonKGKTFwM6NhW5ykKxlaHORz3ai5IqRBUsbNyrkjflEurNYpjTbcq5OD22Sb1t5f0ZDN0+L03ykQpFzBY8Muh8igvlROfmcR5nCWFPTsXu3M5FRfq427xM2mRkHqryaHWUUR5pRS4auFz93EisPdfGryBujmV5NRyIol5+pwKCk0ogt3XxNCOCd3lIAoXXBMiiemBQHqgvcFvhLwHEhlajhu+L6VS+XfueV63+TcXBfU41WiWvNefvJWHUYsfqX6d86eo+L0PD9L2SJeGVyuiLhng6Ojphmvsvzd6mU2rHdqx3u4PmhaLjp/4p+oYBI7cn8r7ONPr0G0UQ2iRvndNV9q+R/ZH2nzd1VO98f3INtNt+LqaN5OG9fzlzxPef1zczU57v5H0fKtP3X8d8eVKy0LLofRqBMd1YOUhMNp36a/Nr6YdXLEfPf6J+Oe7z6g11tHK82lr+oENLouLkIuVZqvZ0LNRkrEvnn9D/nl53r1d61lfzP68sa7Lno9I9P2cbOHmGXP0o/RX56fRD6DyLTX7BEc/oRjGdS56rdsY2bt87K0ZdktWwPDNt/cPjP2d9D8/WaHoGTfReBirGiutNtXjKKCy0KUzpkPUKvVJ4VZ9k4T6Lzqcz/R6BUeI8T1vzjnbSMsMPxdshYYexaQ+dGeaRt3qby56q1wk1+Wy3gjmP+J/riRF086TSXSpPImbiPT89AjoeLsZEllNoruy51pf2XysBAWCG/QPifDVhpVnY+5qsS49weJvbshJJq60w8iV+Bm/V81Gj3prmUK3yub6K8tqhbdsq5Vb+itoT5T+k/LPD6EFMScb4va0I/dkCodPplaUYL1lJljWmk2qaoUxpMqIyfREPG3RpntULPMOaxqr2bb6NEztLXKUUpTsmcdRCl3MGqZYmwoNHVjNrZTxecyWmPZqgP5ou0M1moKV30Ize89HxD7JrJJvBwTG9Fz1zC2Ui3cmrqbQf+hikoDhoZBpVUXtrTyKrZGsTumn0E8LfYn5z0/aXhD3x40+W+n+OVK1/GIep3rP7/5/P6g+q/yT+oD59ibyjJ8yRxO5JyoKQNxgEwHzsphMIhhMIomFaJ8qEtEFS3mmVUHmlyhXmQFOQmCgAnygIT5QAS5TgRFQATE/DJxxNAWAcew3FLl1iQQrFMqna8qJVikJcoR5lKqVogKlYnygTafH4EgUAZCqA80gP1BCLFBEDihPh4KsJ+5vWDjcIpuM2UR5Iph5ruEwFHhAB7mcYQR3H5BBPxJDcLA4ec9w8juEAATBUlMPCKJuEUwiwvG4CiYwEA4tEMPNdxhQURFgCYQKJhGYSmy1UMQ8dRuMrh1pC6U5fRZc/LweywF2y5PQEAUTQE450VJ4O+EYMszjYpygI7Z0M6wTexI+d6VfTmkuPpjlwNlQpLc5duoZ3vg/Idz08iBXZ7zSkE1+vmcCsb1PKb8568irJmLVKBunz0k10+3yUjGLvyAAH0w5ZDp1dC0Lj0vjMOi3pWwa5KplLtzCCYac5iAWp7g6zhKcoDiqWRd48uTYZ5A8T/X+NcKGvDa+orWo6DWisChXtsV6xKx9T9YvUHmj05zbeWIyLYrG0N4Jq5u8fUU7mzeofG/sLK7fjW2Yf1cfi3Vsr2P+a/2uNK5L8T7cKR0Pq8jJvOsOXWr+0fKHr79G+TtT5B/5/sR7d+34dwiJ6K9vy4prJNuXpZWeGtvqcaBzK/t/495Wz/Uc3Lrz5KYx1qhZFbLV39Dfnr9EN8Izx77C+e3d5+0kqB86uLjP3CdyWzFmLSa2qvOvuSJnYOKxL57/AEN+f/L6NNnk5n84+sq752/wtp02l3c9XbTqXLsw+h3gr3r7nlXBJxEx1yzumx/NV+nsZtXbwuY+ooztc21aNc3j0h5G9ge54NYynWc+97xvNcgLvokBfJSk1FFhQ5HiDpx6R86+kcqnc+0Sgo8WYP6FwuNMeG2QfD1PrDHzekPX5H261/1f5b9T3zyz9krlszMyU/H/ANQclbkyp06iLxlvHIXmWw1zUNaP8/6+ONNegeqM00FpIfo3wtXipiK/T/gPCNlgLRoEBz1yn7g8T+4MkksmLw8X0S/Vv1vPrt9rdYU6DH1qd0I6qXtGaqsJePmvreOLtz/Meui5M5tRbOyu5zgZJ+rqiTcMbpxkujjpWFOuoaaXZWpzLzmj1N5oxUeSVZtk05nSKc4taeesU9kVqcRPx59s5JKOLRKoVfslY2JlLI8Xi0VDzDud0qmLzsdLEyg0N3TZYY2OArrV7ZZdq8XR9CU1vfm8wxNzb8ffWg0KLms5t12QqYZU07ZXzTDKtWf6KPzxfpv+K9KvYd6Bwz5z6H4r+fPYnjvq303RM50jzeXRvsV8TftHHJ6Ci7BEXztuOLgnHEkhhFIFAOmA8YQH401wiedyJrlGgCgXzJgsRpMFOJTBQAT5QATBUoEBQCU+U40S4/IJyh1SJj9OhCKcBOMAiCcFSfHKwgG4RAUAlPlCgmCnAlygAmChQTA/CS5TiEyrFBMFOYiCxU0uU4uo8ceb1CccRl4ea7jdIHCLO7hYA8ZQHCLA4RADAICHCIBA4cAiBeMKCiItFE3CLxhAOEWiCYXBeNzZREWiiYUFERYU3GAhjcBRMBPDxgAeEOUIZUZVAZ0fLxq/B7T0UFOH2VOIMaEBQOXuai4Hl6URW7SSpODVmxWWMJuV4NywF0GWrNtL9npDJzI46QPTwyoJGxDLgJORV7OKPXcj2cpBVDoyMZAvf5DoUnE6lMIY9ZQUDflTKr2nMgRyn2eWkU5OrzeHuEJTBZwgAhDhmi8YtUUFez6ECujjYmkFZ2i1ZSQVwsxYvmh6vB7E+Q2cu/qOJ6yj2HJ7StUcMOrCCrllY9GNcrNmr+nNV2Nngcz6+enPMXqLHXy2E5G6caSD5igGD1lech6JwL0VjtL4huWH64eLthxXUP52/YrUZhJfH+7DIMVPU41mSJeTVr698i+t/vfl70/JNc3owKNgb4Nizm4f2PLRBky5+mdsmeaV389fMRf9m/KvIWU7RVjSiqX+PwvPkr1Gzoh9HfBfv684jwx7w8W9vDYVlTvIqp+m2jCUb1LtpJly6PXMJNwOVY58+vob8++X0vNKhjfO+7IaNg9q4ev0c0z2tc96itQbP4vVJe+/Cf0A9vzJpo/b83eyQkUOTWPmGEt6XnUxlKNMtUCO+bS9nePvYH0/zNZzPUs0+i+d8jKayptWUF1NUvOu0hWYztLQTl596zwj0NmrDQNAo15+HMN9N+WM9C1RNTm2sM/XbLtnJuUX9PYvU3lr1RWcmoVbDeEUA34b+wgksljaV2pNr5Om0FbRWRZSVmc8L2CRU3DduMZbKVeP1D8/rUTNRP6x+beA7tDXGtIoXx3mx9z+JfbctFu5Y683gt++pHpefOtomWvJSpWxEqIkyVjV518')
GO