USE [master]
GO
-- Check if the database "PropNote" exists
IF DB_ID('PropNote') IS NOT NULL
BEGIN
    -- Drop the database if it exists
    ALTER DATABASE PropNote SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PropNote;
END
/****** Object:  Database [PropNote]    Script Date: 2023/07/27 11:38:26 ******/
CREATE DATABASE [PropNote]
GO
ALTER DATABASE [PropNote] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PropNote] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PropNote] SET ARITHABORT OFF 
GO
ALTER DATABASE [PropNote] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PropNote] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PropNote] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PropNote] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PropNote] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PropNote] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PropNote] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PropNote] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PropNote] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PropNote] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PropNote] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PropNote] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PropNote] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PropNote] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PropNote] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PropNote] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PropNote] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PropNote] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PropNote] SET  MULTI_USER 
GO
ALTER DATABASE [PropNote] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PropNote] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PropNote] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PropNote] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PropNote] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PropNote] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PropNote] SET QUERY_STORE = OFF
GO
USE [PropNote]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCESS](
	[AccessID] [int] IDENTITY(1,1) NOT NULL,
	[AccessName] [varchar](50) NOT NULL,
	[AccessDescription] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AccessID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[AdminID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[Name] [varchar](100) NOT NULL,
	[PhoneNumber] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BROKER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BROKER](
	[BrokerID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Surname] [varchar](100) NOT NULL,
	[PhoneNumber] [varchar](10) NOT NULL,
	[OfficeAddress] [varchar](50) NOT NULL,
	[LicenseNumber] [varchar](100) NOT NULL,
	[CommissionRate] [decimal](5, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BrokerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTRACTOR]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTRACTOR](
	[ContractorID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[ContractorTypeID] [int] NULL,
	[AreaOfBusiness] [varchar](100) NULL,
	[Availability] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ContractorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTRACTORTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTRACTORTYPE](
	[ContractorTypeID] [int] IDENTITY(1,1) NOT NULL,
	[ContractorTypeName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ContractorTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Correspondance]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CORRESPONDANCE](
	[CorrespondanceID] [int] IDENTITY(1,1) NOT NULL,
	[CorrespondanceName] [varchar](100) NULL,
	[CorrespondanceDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[CorrespondanceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPOSIT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPOSIT](
	[DepositID] [int] IDENTITY(1,1) NOT NULL,
	[LeaseID] [int] NOT NULL,
	[Amount] [decimal](10,2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DepositID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Discount]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISCOUNT](
	[DiscountID] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[DiscountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Help]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HELP](
	[HelpID] [int] IDENTITY(1,1) NOT NULL,
	[FK_HelpCategoryID] [int] NULL,
	[HelpDescription] [varchar](50) NULL,
	[HelpVideo] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[HelpID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HelpCategory]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HELPCATEGORY](
	[HelpCategoryID] [int] IDENTITY(1,1) NOT NULL,
	[HelpCategoryDescription] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[HelpCategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LEASE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LEASE](
	[LeaseID] [int] IDENTITY(1,1) NOT NULL,
	[TenantID] [int] NULL,
	[PropertyID] [int] NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[MonthlyAmount] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[LeaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCE](
	[MaintenanceID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[ContractorID] [int] NULL,
	[MaintenanceStatusID] [int] NOT NULL,
	[MaintenanceTypeID] [int] NOT NULL,
	[MaintenanceDate] [date] NOT NULL,
	[MaintenanceTime] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DOCUMENT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DOCUMENT](
	[DocumentID] [int] IDENTITY(1,1) NOT NULL,
	[TenantID] [int] NULL,
	[DocumentName] [varchar](max) NULL,
	[FileData] [varbinary](max) NULL,
	[UploadDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[DocumentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCESTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCESTATUS](
	[MaintenanceStatusID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCETYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCETYPE](
	[MaintenanceTypeID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceTypeName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCENOTE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCENOTE](
	[MaintenanceNoteID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceID] [int] NOT NULL,
	[MaintenanceNoteDescription] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaintenanceNoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEETING]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEETING](
	[MeetingID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](50) NOT NULL,
	[Date] [date] NOT NULL,
	[Time] [time](7) NOT NULL,
	[MeetingType] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEETINGMEMBERLINE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEETINGMEMBERLINE](
	[MeetingMemberID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingMemberID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEMBER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEMBER](
	[MeetingMemberID] [int] IDENTITY(1,1) NOT NULL,
	[MeetingMember] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MeetingMemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[NotificationID] [int] IDENTITY(1,1) NOT NULL,
	[NotificationTypeID] [int] NULL,
	[ReccurenceTypeID] [int] NULL,
	[NotificationName] [varchar](50) NULL,
	[NotificationDate] [date] NULL,
	[StartTime] [time] NULL,
	[EndTime] [time] NULL,
	[Description] [varchar](max)
PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATIONTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATIONTYPE](
	[NotificationTypeID] [int] IDENTITY(1,1) NOT NULL,
	[NotificationTypeDescription] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificationTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROBLEM]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEM](
	[ProblemID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionID] [int] NOT NULL,
	[ProblemStatusID] [int] NOT NULL,
	[ProblemSubject] [varchar](32) NULL,
	[ProblemDescription] [varchar](100) NULL,
	[ProblemDate] [date] NULL,
	[ProblemSeverity] [varchar](20)
PRIMARY KEY CLUSTERED 
(
	[ProblemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemPhoto]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMPHOTO](
	[ProblemPhotoID] [int] IDENTITY(1,1) NOT NULL,
	[ProblemID] [int] NOT NULL,
	[ImageName] [varchar](max) NULL,
	[ImageData] [varchar] (max),
	[UploadDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemPhotoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemStatus]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMSTATUS](
	[ProblemStatusID] [int] IDENTITY(1,1) NOT NULL,
	[ProblemStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProblemVideo]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROBLEMVIDEO](
	[ProblemVideoID] [int] IDENTITY(1,1) NOT NULL,
	[ProblemID] [int] NOT NULL,
	[FileName] [nvarchar](255) NULL,
	[ContentType] [nvarchar](100) NULL,
	[UploadDate] [date] NULL,
	[VideoData] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProblemVideoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTY]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTY](
	[PropertyID] [int] IDENTITY(1,1) NOT NULL,
	[BrokerID] [int] NULL,
	[PropertyStatusID] [int] NULL,
	[Description] [varchar](100) NULL,
	[BuildingNumber] [int] NULL,
	[Street] [varchar](100) NULL,
	[Suburb] [varchar](100) NULL,
	[PurchaseAmount] [decimal](20, 2) NULL,
	[PurchaseYear] [int] NULL,
	[Size] [decimal](10, 2) NULL,
	[Yard] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTYIMAGE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTYIMAGE](
	[PropertyImageID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[ImageName] [varchar](max) NULL,
	[ImageData] nvarchar(max),
PRIMARY KEY CLUSTERED 
(
	[PropertyImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROPERTYSTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROPERTYSTATUS](
	[PropertyStatusID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyStatusName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[PropertyStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recovery]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERY] (
	[RecoveryID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NULL,
	[RecoveryTypeID] [int] NULL,
	[RecoveryDescription] [varchar](50) NULL,
	[RecoveryAmount] [decimal] (10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[RecoveryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECOVERYTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECOVERYTYPE] (
	[RecoveryTypeID] [int] IDENTITY(1,1) NOT NULL,
	[RecoveryTypeDescription] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[RecoveryTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTION]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTION] (
	[InspectionID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NULL,
	[EmployeeID] [int] NULL,
	[InspectionTypeID] [int] NULL,
	[InspectionStatusID] [int] NULL,
	[InspectionDescription] [varchar] (50) NULL,
	[InspectionDate] [date] NULL,
	[InspectionTime] [time] NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTIONSTATUS]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTIONSTATUS] (
	[InspectionStatusID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionStatusName] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INSPECTIONTYPE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSPECTIONTYPE] (
	[InspectionTypeID] [int] IDENTITY(1,1) NOT NULL,
	[InspectionTypeName] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[InspectionTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLISTITEM]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLISTITEM](
	[SnagListItemID] [int] IDENTITY(1,1) NOT NULL,
	[SnagListItemDescription] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SnagListItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLIST]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLIST](
	[SnagListID] [int] IDENTITY(1,1) NOT NULL,
	[PropertyID] [int] NOT NULL,
	[SnagListDescription] [varchar](100) NULL,
	[SnagListCreated] [date],
	[SnagListModified] [date],
PRIMARY KEY CLUSTERED 
(
	[SnagListID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SNAGLISTITEMLINE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SNAGLISTITEMLINE](
	[SnagListID] [int] NOT NULL,
	[SnagListItemID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SnagListID] ASC,
	[SnagListItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[RECCURENCEITEMTYPE]]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECCURENCEITEMTYPE](
	[ReccurenceTypeID] [int] IDENTITY(1,1) NOT NULL,
	[ReccurenceTypeDescription] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ReccurenceTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHEDULE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHEDULE](
	[NotificationID]  [int] NOT NULL,
	[UserID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TENANT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TENANT](
	[TenantID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[CompanyName] [varchar](100) NULL,
	[CompanyNumber] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[TenantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[JobTitle] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAccess]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERACCESS](
	[RoleID] [int] NOT NULL,
	[AccessID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[AccessID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERMEETING]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERMEETING](
	[UserID] [int] NOT NULL,
	[MeetingID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MeetingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERROLE]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERROLE](
	[RoleID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](255) NOT NULL,
	[Password] [varchar](255) NOT NULL,
	[ProfilePhoto] [varchar](max) NULL,
	[Email] [varchar](255) NOT NULL,
	[Name] [varchar](255) NULL,
	[Surname] [varchar](255) NULL,
	[PhoneNumber] [varchar](10) NULL,
	[HasLoggedIn] [bit] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VAT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAT](
	[VATID] [int] IDENTITY(1,1) NOT NULL,
	[Percentage] [decimal](5, 2) NULL,
	[Date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[VATID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYMENT]    Script Date: 2023/07/27 11:38:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[PaymentID] [int] IDENTITY(1,1) NOT NULL,
	[MaintenanceID] [int] NOT NULL,
	[Amount] [decimal] (10,2) NULL,
PRIMARY KEY CLUSTERED 
(
	[PaymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENT] WITH CHECK ADD FOREIGN KEY([MaintenanceID])
REFERENCES [dbo].[MAINTENANCE] ([MaintenanceID])
GO
ALTER TABLE [dbo].[ADMIN] WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[CONTRACTOR]  WITH CHECK ADD FOREIGN KEY([ContractorTypeID])
REFERENCES [dbo].[CONTRACTORTYPE] ([ContractorTypeID])
GO
ALTER TABLE [dbo].[CONTRACTOR]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[DEPOSIT]  WITH CHECK ADD FOREIGN KEY([LeaseID])
REFERENCES [dbo].[LEASE] ([LeaseID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HELP]  WITH CHECK ADD FOREIGN KEY([FK_HelpCategoryID])
REFERENCES [dbo].[HELPCATEGORY] ([HelpCategoryID])
GO
ALTER TABLE [dbo].[LEASE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[LEASE]  WITH CHECK ADD FOREIGN KEY([TenantID])
REFERENCES [dbo].[TENANT] ([TenantID])
GO
ALTER TABLE [dbo].[SCHEDULE] WITH CHECK ADD FOREIGN KEY([NotificationID])
REFERENCES [dbo].[NOTIFICATION] ([NotificationID])
GO
ALTER TABLE [dbo].[SCHEDULE] WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD FOREIGN KEY([ReccurenceTypeID])
REFERENCES [dbo].[RECCURENCEITEMTYPE] ([ReccurenceTypeID])
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD FOREIGN KEY([NotificationTypeID])
REFERENCES [dbo].[NOTIFICATIONTYPE] ([NotificationTypeID])
GO
ALTER TABLE [dbo].[MEETINGMEMBERLINE]  WITH CHECK ADD FOREIGN KEY([MeetingMemberID])
REFERENCES [dbo].[MEMBER] ([MeetingMemberID])
GO
ALTER TABLE [dbo].[MEETINGMEMBERLINE]  WITH CHECK ADD FOREIGN KEY([MeetingID])
REFERENCES [dbo].[MEETING] ([MeetingID])
GO
ALTER TABLE [dbo].[PROPERTY]  WITH CHECK ADD FOREIGN KEY([BrokerID])
REFERENCES [dbo].[BROKER] ([BrokerID])
GO
ALTER TABLE [dbo].[PROPERTY]  WITH CHECK ADD FOREIGN KEY([PropertyStatusID])
REFERENCES [dbo].[PROPERTYSTATUS] ([PropertyStatusID])
GO
ALTER TABLE [dbo].[PROPERTYIMAGE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[TENANT]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERACCESS]  WITH CHECK ADD FOREIGN KEY([AccessID])
REFERENCES [dbo].[ACCESS] ([AccessID])
GO
ALTER TABLE [dbo].[USERACCESS]  WITH CHECK ADD FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLE] ([RoleID])
GO
ALTER TABLE [dbo].[USERMEETING]  WITH CHECK ADD FOREIGN KEY([MeetingID])
REFERENCES [dbo].[MEETING] ([MeetingID])
GO
ALTER TABLE [dbo].[USERMEETING]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERROLE]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[USERROLE]  WITH CHECK ADD FOREIGN KEY([RoleID])
REFERENCES [dbo].[ROLE] ([RoleID])
GO
ALTER TABLE [dbo].[PROBLEMVIDEO]  WITH CHECK ADD FOREIGN KEY([ProblemID])
REFERENCES [dbo].[PROBLEM] ([ProblemID])
GO
ALTER TABLE [dbo].[PROBLEMPHOTO]  WITH CHECK ADD FOREIGN KEY([ProblemID])
REFERENCES [dbo].[PROBLEM] ([ProblemID])
GO
ALTER TABLE [dbo].[PROBLEM]  WITH CHECK ADD FOREIGN KEY([InspectionID])
REFERENCES [dbo].[INSPECTION] ([InspectionID])
GO
ALTER TABLE [dbo].[PROBLEM]  WITH CHECK ADD FOREIGN KEY([ProblemStatusID])
REFERENCES [dbo].[PROBLEMSTATUS] ([ProblemStatusID])
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[USER] ([UserID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([ContractorID])
REFERENCES [dbo].[CONTRACTOR] ([ContractorID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([MaintenanceStatusID])
REFERENCES [dbo].[MAINTENANCESTATUS] ([MaintenanceStatusID])
GO
ALTER TABLE [dbo].[MAINTENANCE]  WITH CHECK ADD FOREIGN KEY([MaintenanceTypeID])
REFERENCES [dbo].[MAINTENANCETYPE] ([MaintenanceTypeID])
GO
ALTER TABLE [dbo].[MAINTENANCENOTE]  WITH CHECK ADD FOREIGN KEY([MaintenanceID])
REFERENCES [dbo].[MAINTENANCE] ([MaintenanceID])
GO
ALTER TABLE [dbo].[SNAGLISTITEMLINE]  WITH CHECK ADD FOREIGN KEY([SnagListItemID])
REFERENCES [dbo].[SNAGLISTITEM] ([SnagListItemID])
GO
ALTER TABLE [dbo].[SNAGLISTITEMLINE]  WITH CHECK ADD FOREIGN KEY([SnagListID])
REFERENCES [dbo].[SNAGLIST] ([SnagListID])
GO
ALTER TABLE [dbo].[SNAGLIST]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[RECOVERY]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[RECOVERY]  WITH CHECK ADD FOREIGN KEY([RecoveryTypeID])
REFERENCES [dbo].[RECOVERYTYPE] ([RecoveryTypeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([PropertyID])
REFERENCES [dbo].[PROPERTY] ([PropertyID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([InspectionTypeID])
REFERENCES [dbo].[INSPECTIONTYPE] ([InspectionTypeID])
GO
ALTER TABLE [dbo].[INSPECTION]  WITH CHECK ADD FOREIGN KEY([InspectionStatusID])
REFERENCES [dbo].[INSPECTIONSTATUS] ([InspectionStatusID])
GO
ALTER TABLE [dbo].[DOCUMENT]  WITH CHECK ADD FOREIGN KEY([TenantID])
REFERENCES [dbo].[TENANT] ([TenantID])
GO
USE [master]
GO
ALTER DATABASE [PropNote] SET  READ_WRITE 
GO

USE [PropNote]
GO
/*Add Seed Data*/
INSERT INTO [dbo].[ROLE]([Name])VALUES('Admin');
INSERT INTO [dbo].[ROLE]([Name])VALUES('Tenant');
INSERT INTO [dbo].[ROLE]([Name])VALUES('Contractor');
GO

INSERT INTO [dbo].[BROKER]
           ([Name]
           ,[Surname]
           ,[PhoneNumber]
           ,[OfficeAddress]
           ,[LicenseNumber]
           ,[CommissionRate])
     VALUES
           ('Eric'
           ,'Jarvie'
           ,'0815245184'
           ,'510 Durban Road'
           ,'6524548'
           ,2.5)
GO

INSERT INTO [dbo].[PROPERTYSTATUS]
           ([PropertyStatusName])
     VALUES
           ('Avaliable')
GO

INSERT INTO [dbo].[PROPERTY]
           ([BrokerID]
           ,[PropertyStatusID]
           ,[Description]
           ,[BuildingNumber]
           ,[Street]
           ,[Suburb]
           ,[PurchaseAmount]
           ,[PurchaseYear]
           ,[Size]
           ,[Yard])
     VALUES
           (1
           ,1
           ,'Factory'
           ,10
           ,'54'
           ,'Durban'
           ,2000000
           ,2018
           ,698
           ,3.6)
GO

INSERT INTO [dbo].[USER]
           ([Username]
           ,[Password]
           ,[ProfilePhoto]
           ,[Email]
           ,[Name]
           ,[Surname]
           ,[PhoneNumber]
           ,[HasLoggedIn])
     VALUES
           ('pip'
           ,'DEE6669875FFA6D6A8F8AD53DF4908E542780F2FC4221D6DE6958FCAF49D6E73'
           ,null
           ,'pipsjarvie@gmail.com'
           ,'Pippa'
           ,'Jarvie'
           ,'0835421542'
           ,1)
GO

INSERT INTO [dbo].[TENANT]
			([UserID]
			,[CompanyName]
			,[CompanyNumber])
	VALUES
			(1
			,'FiveAgents'
			,'0784563259')

INSERT INTO [dbo].[USER]
           ([Username]
           ,[Password]
           ,[ProfilePhoto]
           ,[Email]
           ,[Name]
           ,[Surname]
           ,[PhoneNumber]
           ,[HasLoggedIn])
     VALUES
           ('admin'
           ,'DEE6669875FFA6D6A8F8AD53DF4908E542780F2FC4221D6DE6958FCAF49D6E73'
           ,null
           ,'admin@gmail.com'
           ,'Admin'
           ,'admin'
           ,'0835421542'
           ,1)
GO

INSERT INTO [dbo].[USERROLE]
           ([RoleID]
           ,[UserID])
     VALUES
           (1
           ,1)
GO

INSERT INTO [dbo].[RECOVERYTYPE]
           ([RecoveryTypeDescription])
     VALUES
           ('Council Rates')

GO

INSERT INTO [dbo].[INSPECTIONSTATUS]
           ([InspectionStatusName])
     VALUES
           ('To Do')

GO

INSERT INTO [dbo].[INSPECTIONSTATUS]
           ([InspectionStatusName])
     VALUES
           ('In Progress')

GO

INSERT INTO [dbo].[INSPECTIONSTATUS]
           ([InspectionStatusName])
     VALUES
           ('Completed')

GO

INSERT INTO [dbo].[INSPECTIONTYPE]
           ([InspectionTypeName])
     VALUES
           ('Brief Check Up')

GO

INSERT INTO [dbo].[INSPECTIONTYPE]
           ([InspectionTypeName])
     VALUES
           ('Thorough Walk Through')

GO

INSERT INTO [dbo].[PROBLEMSTATUS]
           ([ProblemStatusName])
     VALUES
           ('To Deal With')
GO

INSERT INTO [dbo].[PROBLEMSTATUS]
           ([ProblemStatusName])
     VALUES
           ('In Progress')

GO

INSERT INTO [dbo].[PROBLEMSTATUS]
           ([ProblemStatusName])
     VALUES
           ('Dealt With')

GO

INSERT INTO [dbo].[PROBLEMSTATUS]
           ([ProblemStatusName])
     VALUES
           ('No longer a problem')
GO
