name: Angular Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: Angular
    

    strategy:
      matrix:
        node-version: [18.x]

    steps:  
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
            Angular:
              - 'Angular/**'
              
    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.filter.outputs.Angular == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
        
    - name: Install Dependecies
      if: steps.filter.outputs.Angular == 'true'
      run: npm i
      
    - name: Run Build
      if: steps.filter.outputs.Angular == 'true'
      run: npm run build --if-present
